In [1]:
import requests
import os
import json
import pandas as pd
from dotenv import load_dotenv, dotenv_values
from requests.exceptions import HTTPError, ConnectionError, Timeout, RequestException
from pathlib import Path

In [2]:
load_dotenv(Path.cwd().parent / ".env")

False

In [3]:
URL_BASE = "https://api.company-information.service.gov.uk"
URL_META_DATA = "https://document-api.company-information.service.gov.uk/document"
TIMEOUT = 10  # seconds

In [4]:
#Company House

def get(endpoint, params=None, headers=None):
    url = f"{URL_BASE}/{endpoint}"
    response = requests.get(
        url,
        auth=(os.getenv("CH_API"),""),
        headers=headers,
        params=params,
        timeout=TIMEOUT
        )
    response.raise_for_status()
    print(response.status_code)
    return response.json()

In [5]:
print(Path.cwd().parent.parent / '.env')

/Users/natchalin_/Projects/final_project/Lloyds/.env

In [6]:
import time, threading, itertools, re
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm.auto import tqdm      

# --- Multi-key throttled Companies House client (uses all API keys -> ~Nx faster)

def _clean_key(v):
    """Pull out the cleaned keys"""
    v = v.strip()
    m = re.search(r"""['"]([^'"]+)['"]""", v)   # value inside the first quote pair
    return m.group(1) if m else v.rstrip(",").strip()


def _load_ch_keys(names = ('CH_API', 'CH_API_2', 'CH_API_3', 'CH_API_4')):
    parsed = []
    env = Path.cwd().parent.parent / '.env'
    env_text = env.read_text()
    env_text_line = env_text.splitlines()
    
    for lines in env_text_line:
        k, v = lines.split('=', 1)
        parsed.append(_clean_key(v))
        
    return parsed


_KEYS = _load_ch_keys()
if not _KEYS:
    raise RuntimeError("No Companies House API keys found (checked .env and env vars)")

_MIN_INTERVAL = 0.6           # seconds between calls PER KEY (~1.7/s; CH cap 2.0/s each)
MAX_WORKERS   = 2 * len(_KEYS)
print(f"{len(_KEYS)} API key(s) loaded -> up to ~{len(_KEYS) / _MIN_INTERVAL:.1f} req/s "
      f"with {MAX_WORKERS} workers")


class _Lane:
    """One API key: dedicated Session + a lock enforcing min-interval pacing."""
    __slots__ = ("session", "lock", "last")
    def __init__(self, key):
        self.session = requests.Session(); self.session.auth = (key, "")
        self.lock = threading.Lock(); self.last = 0.0
    def pace(self):
        with self.lock:
            wait = _MIN_INTERVAL - (time.monotonic() - self.last)
            if wait > 0:
                time.sleep(wait)
            self.last = time.monotonic()


_LANES = [_Lane(k) for k in _KEYS]
_rr = itertools.count(); _rr_lock = threading.Lock()

def _next_lane():
    with _rr_lock:
        i = next(_rr)
    return _LANES[i % len(_LANES)] # Return lane number (0 - 3) given the next count on the _rr (ticket dispenser)


def ch_get(path, params=None, max_retries=5):
    """Thread-safe, key-rotating, throttled GET. Returns a Response (200/404/etc.
       for the caller to interpret) or None if it gave up. Handles 429 (waits out
       the window) and transient network/5xx errors with exponential backoff."""
    url = f"{URL_BASE}{path}"
    for attempt in range(max_retries):
        lane = _next_lane()
        lane.pace()
        try:
            r = lane.session.get(url, params=params, timeout=TIMEOUT)
        except (ConnectionError, Timeout):
            time.sleep(2 ** attempt); continue
        if r.status_code == 429:                       # rare with per-key pacing
            time.sleep(int(r.headers.get("Retry-After", 60)) + 1); continue
        if r.status_code >= 500:                        # transient server error
            time.sleep(2 ** attempt); continue
        return r
    return None


def parallel_fill(df, todo_index, fn, cols, out_path,
                  desc="fetch", max_workers=None, checkpoint_every=200):
    """Concurrently apply fn(com_num) over todo_index rows and write results into
       `cols` (str, or list matching fn's tuple return). Only network I/O runs in
       threads; all DataFrame writes + checkpoints happen on the main thread, so no
       df locking is needed. Resumable + checkpointed + live rate/ETA."""
    cols = [cols] if isinstance(cols, str) else list(cols)
    todo_index = list(todo_index)
    n_todo = len(todo_index)
    workers = max_workers or MAX_WORKERS
    print(f"{n_todo} to fetch (of {len(df)}) — {len(_LANES)} keys x {workers} workers")
    t0 = time.time(); done = 0
    with ThreadPoolExecutor(max_workers=workers) as ex:
        fut2idx = {ex.submit(fn, df.at[idx, "com_num"]): idx for idx in todo_index}
        for fut in tqdm(as_completed(fut2idx), total=n_todo, desc=desc):
            idx = fut2idx[fut]
            try:
                res = fut.result()
            except Exception:
                res = "error" if len(cols) == 1 else tuple("error" for _ in cols)
            if len(cols) == 1:
                df.at[idx, cols[0]] = res
            else:
                for c, v in zip(cols, res):
                    df.at[idx, c] = v
            done += 1
            if done % checkpoint_every == 0:
                df.to_csv(out_path, index=False)
                rate = done / (time.time() - t0)
                eta = (n_todo - done) / rate / 60 if rate else 0
                print(f"  {done}/{n_todo} | {rate:.2f}/s | ETA ~{eta:.0f} min | checkpoint saved")
    if n_todo:                       # nothing fetched -> nothing changed -> skip the write
        df.to_csv(out_path, index=False)
        print(f"Saved -> {out_path}")
    else:
        print(f"Nothing to fetch — {out_path} left untouched.")

4 API key(s) loaded -> up to ~6.7 req/s with 8 workers

/opt/miniconda3/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Stage 1: profile pull — `account_type` + `accounts_overdue` + panel fields (one call)

Scans **every** CSV in `company_data/company_raw/`, dedupes on `com_num`, and pulls the company profile **only for new company numbers**. One `/company/{num}` call now yields **six** columns — the original two plus the point-in-time **panel fields**, at zero extra API cost:

- `account_type`, `accounts_overdue`
- `date_of_creation` — incorporation date → `age@T` for the panel
- `company_status` — active / dissolved / liquidation (drop non-active from lead lists)
- `last_accounts_made_up_to`, `next_accounts_due_on` — point-in-time accounts recency / punctuality

Output → `company_data/company_with_acctype/com_names_with_acctype_test.csv`

In [7]:
# --- Stage 1: ONE profile call per NEW company -> 6 columns ---------------------

BASE        = Path("company_data")
RAW_DIR     = BASE / "company_raw"
# ONE table for the whole pipeline: every company ever pulled lives here.
# Non-SME rows are kept on purpose — they are the "already checked, do not
# re-pull" cache (154k rows = 6.4h of API calls saved on every rebuild).
COMPANIES   = BASE / "companies.csv"
SME_TYPES   = ["small", "micro-entity", "total-exemption-full",
               "total-exemption-small", "medium"]

PROFILE_COLS = ["account_type", "accounts_overdue",                 
                "date_of_creation", "company_status",               
                "last_accounts_made_up_to", "next_accounts_due_on"]

# 1. Combine every raw file; one row per company (raw files repeat com_num per SIC).
raw = pd.concat([pd.read_csv(f, dtype=str) for f in sorted(RAW_DIR.glob("*.csv"))],
                ignore_index=True).drop_duplicates("com_num")

# 2. Load prior results; NEW companies = those not already processed.
if COMPANIES.exists():
    done = pd.read_csv(COMPANIES, dtype=str)
else:
    done = pd.DataFrame(columns=list(raw.columns))
for c in PROFILE_COLS:
    if c not in done.columns:
        done[c] = pd.NA          

new = raw[~raw["com_num"].isin(done["com_num"])].copy() # Create a copy rows that 'raw' is not in 'done'

for c in PROFILE_COLS:
    new[c] = pd.NA              # Create the profile cols as place holders

df = pd.concat([done, new], ignore_index=True)   # keep old results, append new rows

df = df.drop(columns=[c for c in ["com_type", "town", "county"]  # unused raw passthrough
                      if c in df.columns])


def fetch_profile_fields(company_num):
    """All six columns from ONE profile call.
       Sentinels: 'no_accounts', 'not_found', 'error', 'unknown', 'none'."""
    r = ch_get(f"/company/{str(company_num).strip()}")
    if r is None:              return ("error",) * 6 # 6 columns -> need to show 6 errors
    if r.status_code == 404:   return ("not_found",) * 6
    if r.status_code != 200:   return ("error",) * 6
    j = r.json()
    acc = j.get("accounts", {})
    la  = acc.get("last_accounts", {})
    ov  = acc.get("overdue")
    return (la.get("type") or "no_accounts",
            "unknown" if ov is None else str(ov),
            j.get("date_of_creation") or "unknown",
            j.get("company_status") or "unknown",
            la.get("made_up_to") or "none",
            acc.get("next_accounts", {}).get("due_on") or "none")


# Fetch only rows missing account_type (new companies + any interrupted ones).
todo = df.index[df["account_type"].isna()] # Account_type is used for checking the blank info cells
print(f"{len(new)} new companies from raw | {len(done)} already done")
parallel_fill(df, todo, fetch_profile_fields, PROFILE_COLS, COMPANIES, desc="profile")

# the SME flag replaces the old separate SME file — recomputed every run so a
# corrected account_type immediately moves a company in or out of the population
df["is_sme"] = df["account_type"].isin(SME_TYPES)
df.to_csv(COMPANIES, index=False)
print(f"\ncompanies.csv: {len(df):,} rows | is_sme {int(df['is_sme'].sum()):,} "
      f"| non-SME cached {int((~df['is_sme']).sum()):,}")
df["account_type"].value_counts(dropna=False)

0 new companies from raw | 690837 already done
73 to fetch (of 690837) — 4 keys x 8 workers

profile: 100%|██████████| 73/73 [00:10<00:00,  6.71it/s]

Saved -> company_data/companies.csv

companies.csv: 690,837 rows | is_sme 467,363 | non-SME cached 223,474

account_type
micro-entity                   269855
total-exemption-full           187192
no_accounts                    170898
unaudited-abridged              23407
dormant                         10402
full                            10152
small                            9112
audit-exemption-subsidiary       4932
group                            3331
medium                            993
total-exemption-small             211
audited-abridged                  140
null                               73
filing-exemption-subsidiary        63
no-accounts-type-available         44
error                              27
interim                             2
partial-exemption                   2
not_found                           1
Name: count, dtype: int64

In [8]:
# --- Remove perfect duplicate rows from the company table -----------------------
# A "perfect duplicate" = every column identical. The pull already dedupes on
# com_num, so this is now a harmless safety net (expect 0 removed). Operates on
# the WHOLE table (SME + cached non-SME) and writes every row back.
dedup = pd.read_csv(COMPANIES, dtype=str)
before = len(dedup)
dedup = dedup.drop_duplicates()          # all columns must match
removed = before - len(dedup)

dedup.to_csv(COMPANIES, index=False)
print(f"Removed {removed} perfect duplicate row(s): {before} -> {len(dedup)} rows in {COMPANIES}")

Removed 0 perfect duplicate row(s): 690837 -> 690837 rows in company_data/companies.csv

## Stage 2: filter to SME account types (no API calls)

Keep only companies whose `account_type` is one of `small`, `micro-entity`, `total-exemption-full`, `total-exemption-small`, `medium`. Carries forward **every** already-computed enrichment column from the existing SME file, so stage 3 only fetches genuinely new companies. Output → `com_names_sme.csv`.

In [9]:
# --- Stage 2: mark the SME population (no API calls, no second file) -------------
# Previously this REBUILT a separate SME csv from the acctype file, which silently
# dropped any column not listed in CARRY_COLS (that is how `region` kept vanishing).
# With one table there is nothing to rebuild: we just set a flag, so no column can
# ever be lost.
SME_TYPES = ["small", "micro-entity", "total-exemption-full",
             "total-exemption-small", "medium"]
COMPANIES = Path("company_data") / "companies.csv"

# columns the enrichment stages fill in (created lazily so later stages can assume them)
ENRICHED_COLS = ["lloyds_customer", "recent_psc_kind", "recent_charge_status",
                 "recent_charge_created_on", "n_charges", "n_filings",
                 "region", "town_api"]

df = pd.read_csv(COMPANIES, dtype=str, low_memory=False)
df["is_sme"] = df["account_type"].isin(SME_TYPES)
for c in ENRICHED_COLS:
    if c not in df.columns:
        df[c] = pd.NA
df.to_csv(COMPANIES, index=False)

print(f"companies.csv: {len(df):,} rows")
print(f"  is_sme (modelling population): {int(df['is_sme'].sum()):,}")
print(f"  non-SME (kept as re-pull cache): {int((~df['is_sme']).sum()):,}")
print("\naccount types outside the SME set:")
print(df.loc[~df['is_sme'], 'account_type'].value_counts().head(6).to_string())

companies.csv: 690,837 rows
  is_sme (modelling population): 467,363
  non-SME (kept as re-pull cache): 223,474

account types outside the SME set:
account_type
no_accounts                   170898
unaudited-abridged             23407
dormant                        10402
full                           10152
audit-exemption-subsidiary      4932
group                           3331

## Stage 3: SME enrichment — one charges call + one PSC call per company

For each new SME company, **2 API calls** fill **4 columns**:
- `/charges` (paged once) → `lloyds_customer` **and** `recent_charge_status` + `recent_charge_created_on` (previously two separate charges passes)
- `/persons-with-significant-control` → `recent_psc_kind`

`lloyds_customer` matches the whole Lloyds Banking Group ("Lloyds", Bank of Scotland, HBOS, Halifax, AMC, …) but **not** "Lloyd's" of London. "Most recent" = latest `created_on` / `notified_on`. Resumable — only rows missing any of the four are fetched.

**Since the panel work:** the charges call now also **persists the FULL charge list** to `company_info_json/{com_num}_charges.json` while it's already in memory — **zero extra API calls**. That JSON is the raw source for the per-charge history table (**Stage 4**): every charge's `created_on` + lender + status, which the panel needs for the label (Lloyds charge after cutoff T), the existing-customer exclusion (Lloyds charge ≤ T), and the prior-non-Lloyds-borrowing feature (≤ T). Companies enriched *before* this change have no JSON yet — Stage 4 backfills only those.

In [10]:
import re

# --- Stage 3: SME enrichment (multi-key concurrent) ------------------------------
# ONE charges call (paged) + ONE PSC call per company fill FOUR columns:
#   lloyds_customer            <- charges: any charge held by a Lloyds-group entity
#   recent_charge_status       <- charges: most recent charge (latest created_on)
#   recent_charge_created_on   <- charges
#   recent_psc_kind            <- PSC: kind of the PSC with latest notified_on
# (accounts_overdue comes free with the stage-1 profile pull, not here.)
# Resumable: only processes rows still missing ANY of the four.
#
# PANEL: the full charge list is ALREADY in memory here, so we persist it to
# company_info_json/{com_num}_charges.json as we go -- zero extra API calls.
# Stage 4 parses those JSONs into the per-charge history table the panel needs.
#
# Lloyds matching: the token "Lloyds" (no apostrophe) is the bank; it deliberately
# does NOT match "Lloyd's" (apostrophe) = Lloyd's of London, the insurance market.
# List covers the whole Lloyds Banking Group; trim to r"\blloyds\b" for bank-only.
LLOYDS_PATTERNS = [
    r"\blloyds\b",                       # Lloyds Bank, Lloyds TSB, Lloyds Commercial Finance, Lloyds Dev. Capital
    r"bank of scotland",                 # Bank of Scotland plc (Halifax's legal entity too)
    r"\bhbos\b",                         # HBOS plc
    r"agricultural mortgage corp",       # AMC — Lloyds' farm/agri lender
    r"\bhalifax\b",                      # Halifax (division of Bank of Scotland)
    r"birmingham midshires",             # BM — mortgages
    r"cheltenham (?:& |and )gloucester", # C&G — mortgages
    r"bank of wales",                    # historic BoS brand
    r"black horse",                      # Lloyds motor/asset finance
    r"scottish widows",                  # pensions/insurance
    r"\bmbna\b",                         # credit cards (Lloyds acquired 2017)
]
LLOYDS_RE = re.compile("|".join(LLOYDS_PATTERNS), re.I)

COMPANIES = Path("company_data") / "companies.csv"
# The 4 columns Stage 3's enrich_sme() returns. NOT the same list as CARRY_COLS in
# Stage 2 (that one is "what survives a rebuild"); these must match enrich_sme's tuple.
STAGE3_COLS = ["lloyds_customer", "recent_charge_status",
               "recent_charge_created_on", "recent_psc_kind"]
CHARGE_JSON_DIR = Path("company_info_json")      # full charge history persisted here
CHARGE_JSON_DIR.mkdir(exist_ok=True)

sme = pd.read_csv(COMPANIES, dtype=str, low_memory=False)
sme["is_sme"] = sme["is_sme"].astype(str).str.lower().eq("true")
for col in STAGE3_COLS:
    if col not in sme.columns:
        sme[col] = pd.NA


def enrich_sme(company_num):
    """(lloyds_customer, recent_charge_status, recent_charge_created_on,
        recent_psc_kind) — one paged charges call + one PSC call. Also persists
        the FULL charge list to JSON (free: it's already in memory)."""
    cnum = str(company_num).strip()

    # -- charges: single pass yields BOTH the Lloyds flag and the latest charge --
    lloyds, status, created = "False", None, None
    start, charges = 0, []
    while True:
        r = ch_get(f"/company/{cnum}/charges",
                   params={"items_per_page": 100, "start_index": start})
        if r is None:            lloyds = status = created = "error";  break
        if r.status_code == 404: status = created = "no_charges";      break
        if r.status_code != 200: lloyds = status = created = "error";  break
        data = r.json()
        items = data.get("items", [])
        charges.extend(items)
        for ch in items:
            for p in ch.get("persons_entitled", []):
                if LLOYDS_RE.search(p.get("name", "")):
                    lloyds = "True"        # keep paging: still need the latest charge
        start += len(items)
        if not items or start >= data.get("total_count", 0):
            break
    if status is None:                      # paged through wi thout error
        if charges:
            latest = max(charges, key=lambda c: c.get("created_on") or "")
            status = latest.get("status") or "unknown"
            created = latest.get("created_on") or "unknown"
        else:
            status = created = "no_charges"

    # -- persist the FULL charge list while we hold it (zero extra API calls) --
    # (404/no-charges companies get an empty items list = "pulled, none found",
    #  which lets Stage 4 skip them; error paths write nothing so they retry.)
    if status != "error":
        try:
            (CHARGE_JSON_DIR / f"{cnum}_charges.json").write_text(
                json.dumps({"total_count": len(charges), "items": charges}))
        except OSError:
            pass                            # persistence is best-effort

    # -- PSC: kind of the most recent PSC (latest notified_on) --
    rp = ch_get(f"/company/{cnum}/persons-with-significant-control",
                params={"items_per_page": 100})
    if rp is None:              psc = "error"
    elif rp.status_code == 404: psc = "no_psc"
    elif rp.status_code != 200: psc = "error"
    else:
        items = rp.json().get("items", [])
        if not items:
            psc = "no_psc"
        else:
            latest = max(items, key=lambda it: it.get("notified_on") or "")
            psc = latest.get("kind") or "unknown"

    return lloyds, status, created, psc


# SAFETY: the table now holds non-SME companies too. Every todo selection MUST
# be masked by is_sme or this stage would spend ~154k calls enriching companies
# that were deliberately excluded from the population.
todo = sme.index[sme["is_sme"] & sme[STAGE3_COLS].isna().any(axis=1)]
parallel_fill(sme, todo, enrich_sme, STAGE3_COLS, COMPANIES, desc="sme_enrich")
sme[STAGE3_COLS].apply(lambda c: c.value_counts(dropna=False).head(6))

15667 to fetch (of 690837) — 4 keys x 8 workers

sme_enrich:   1%|▏         | 200/15667 [01:01<1:31:07,  2.83it/s]

  200/15667 | 3.25/s | ETA ~79 min | checkpoint saved

sme_enrich:   3%|▎         | 400/15667 [02:01<1:30:39,  2.81it/s]

  400/15667 | 3.28/s | ETA ~78 min | checkpoint saved

sme_enrich:   4%|▍         | 600/15667 [03:02<1:43:34,  2.42it/s]

  600/15667 | 3.29/s | ETA ~76 min | checkpoint saved

sme_enrich:   5%|▌         | 800/15667 [04:02<1:44:59,  2.36it/s]

  800/15667 | 3.30/s | ETA ~75 min | checkpoint saved

sme_enrich:   6%|▋         | 1000/15667 [05:02<1:44:50,  2.33it/s]

  1000/15667 | 3.30/s | ETA ~74 min | checkpoint saved

sme_enrich:   8%|▊         | 1204/15667 [06:03<1:00:35,  3.98it/s]

  1200/15667 | 3.30/s | ETA ~73 min | checkpoint saved

sme_enrich:   9%|▉         | 1404/15667 [07:04<59:35,  3.99it/s]

  1400/15667 | 3.30/s | ETA ~72 min | checkpoint saved

sme_enrich:  10%|█         | 1604/15667 [08:05<58:53,  3.98it/s]

  1600/15667 | 3.30/s | ETA ~71 min | checkpoint saved

sme_enrich:  11%|█▏        | 1800/15667 [09:05<1:22:17,  2.81it/s]

  1800/15667 | 3.30/s | ETA ~70 min | checkpoint saved

sme_enrich:  13%|█▎        | 2001/15667 [10:06<1:39:56,  2.28it/s]

  2000/15667 | 3.30/s | ETA ~69 min | checkpoint saved

sme_enrich:  14%|█▍        | 2201/15667 [11:06<1:32:22,  2.43it/s]

  2200/15667 | 3.30/s | ETA ~68 min | checkpoint saved

sme_enrich:  15%|█▌        | 2401/15667 [12:07<1:31:10,  2.43it/s]

  2400/15667 | 3.30/s | ETA ~67 min | checkpoint saved

sme_enrich:  17%|█▋        | 2603/15667 [13:07<1:05:32,  3.32it/s]

  2600/15667 | 3.30/s | ETA ~66 min | checkpoint saved

sme_enrich:  18%|█▊        | 2801/15667 [14:08<1:31:49,  2.34it/s]

  2800/15667 | 3.30/s | ETA ~65 min | checkpoint saved

sme_enrich:  19%|█▉        | 3000/15667 [15:08<1:26:38,  2.44it/s]

  3000/15667 | 3.30/s | ETA ~64 min | checkpoint saved

sme_enrich:  20%|██        | 3200/15667 [16:08<1:44:24,  1.99it/s]

  3200/15667 | 3.30/s | ETA ~63 min | checkpoint saved

sme_enrich:  22%|██▏       | 3400/15667 [17:08<1:36:36,  2.12it/s]

  3400/15667 | 3.30/s | ETA ~62 min | checkpoint saved

sme_enrich:  23%|██▎       | 3604/15667 [18:09<53:30,  3.76it/s]

  3600/15667 | 3.30/s | ETA ~61 min | checkpoint saved

sme_enrich:  24%|██▍       | 3800/15667 [19:09<1:35:45,  2.07it/s]

  3800/15667 | 3.30/s | ETA ~60 min | checkpoint saved

sme_enrich:  26%|██▌       | 4000/15667 [20:10<1:28:33,  2.20it/s]

  4000/15667 | 3.31/s | ETA ~59 min | checkpoint saved

sme_enrich:  27%|██▋       | 4200/15667 [21:10<1:31:00,  2.10it/s]

  4200/15667 | 3.31/s | ETA ~58 min | checkpoint saved

sme_enrich:  28%|██▊       | 4404/15667 [22:10<49:54,  3.76it/s]

  4400/15667 | 3.31/s | ETA ~57 min | checkpoint saved

sme_enrich:  29%|██▉       | 4600/15667 [23:10<1:19:55,  2.31it/s]

  4600/15667 | 3.31/s | ETA ~56 min | checkpoint saved

sme_enrich:  31%|███       | 4804/15667 [24:11<48:18,  3.75it/s]

  4800/15667 | 3.31/s | ETA ~55 min | checkpoint saved

sme_enrich:  32%|███▏      | 5004/15667 [25:11<46:48,  3.80it/s]

  5000/15667 | 3.31/s | ETA ~54 min | checkpoint saved

sme_enrich:  33%|███▎      | 5200/15667 [26:12<1:06:47,  2.61it/s]

  5200/15667 | 3.31/s | ETA ~53 min | checkpoint saved

sme_enrich:  34%|███▍      | 5404/15667 [27:12<44:15,  3.86it/s]

  5400/15667 | 3.31/s | ETA ~52 min | checkpoint saved

sme_enrich:  36%|███▌      | 5600/15667 [28:13<1:35:54,  1.75it/s]

  5600/15667 | 3.31/s | ETA ~51 min | checkpoint saved

sme_enrich:  37%|███▋      | 5800/15667 [29:13<1:14:22,  2.21it/s]

  5800/15667 | 3.31/s | ETA ~50 min | checkpoint saved

sme_enrich:  38%|███▊      | 6000/15667 [30:13<1:19:05,  2.04it/s]

  6000/15667 | 3.31/s | ETA ~49 min | checkpoint saved

sme_enrich:  40%|███▉      | 6200/15667 [31:15<2:02:56,  1.28it/s]

  6200/15667 | 3.31/s | ETA ~48 min | checkpoint saved

sme_enrich:  41%|████      | 6400/15667 [32:15<1:41:54,  1.52it/s]

  6400/15667 | 3.31/s | ETA ~47 min | checkpoint saved

sme_enrich:  42%|████▏     | 6600/15667 [33:16<1:53:28,  1.33it/s]

  6600/15667 | 3.31/s | ETA ~46 min | checkpoint saved

sme_enrich:  43%|████▎     | 6807/15667 [34:16<39:20,  3.75it/s]

  6800/15667 | 3.31/s | ETA ~45 min | checkpoint saved

sme_enrich:  45%|████▍     | 7000/15667 [35:16<1:46:43,  1.35it/s]

  7000/15667 | 3.31/s | ETA ~44 min | checkpoint saved

sme_enrich:  46%|████▌     | 7200/15667 [36:17<1:47:35,  1.31it/s]

  7200/15667 | 3.31/s | ETA ~43 min | checkpoint saved

sme_enrich:  47%|████▋     | 7400/15667 [37:17<1:57:36,  1.17it/s]

  7400/15667 | 3.31/s | ETA ~42 min | checkpoint saved

sme_enrich:  49%|████▊     | 7600/15667 [38:17<1:40:14,  1.34it/s]

  7600/15667 | 3.31/s | ETA ~41 min | checkpoint saved

sme_enrich:  50%|████▉     | 7800/15667 [39:18<1:36:42,  1.36it/s]

  7800/15667 | 3.31/s | ETA ~40 min | checkpoint saved

sme_enrich:  51%|█████     | 8007/15667 [40:18<31:53,  4.00it/s]

  8000/15667 | 3.31/s | ETA ~39 min | checkpoint saved

sme_enrich:  52%|█████▏    | 8200/15667 [41:18<1:32:47,  1.34it/s]

  8200/15667 | 3.31/s | ETA ~38 min | checkpoint saved

sme_enrich:  54%|█████▎    | 8400/15667 [42:19<1:30:52,  1.33it/s]

  8400/15667 | 3.31/s | ETA ~37 min | checkpoint saved

sme_enrich:  55%|█████▍    | 8600/15667 [43:19<1:26:16,  1.37it/s]

  8600/15667 | 3.31/s | ETA ~36 min | checkpoint saved

sme_enrich:  56%|█████▌    | 8800/15667 [44:19<1:30:02,  1.27it/s]

  8800/15667 | 3.31/s | ETA ~35 min | checkpoint saved

sme_enrich:  57%|█████▋    | 9000/15667 [45:20<1:27:33,  1.27it/s]

  9000/15667 | 3.31/s | ETA ~34 min | checkpoint saved

sme_enrich:  59%|█████▊    | 9200/15667 [46:20<1:30:10,  1.20it/s]

  9200/15667 | 3.31/s | ETA ~33 min | checkpoint saved

sme_enrich:  60%|█████▉    | 9400/15667 [47:20<1:24:01,  1.24it/s]

  9400/15667 | 3.31/s | ETA ~32 min | checkpoint saved

sme_enrich:  61%|██████▏   | 9600/15667 [48:21<1:15:56,  1.33it/s]

  9600/15667 | 3.31/s | ETA ~31 min | checkpoint saved

sme_enrich:  63%|██████▎   | 9800/15667 [49:21<1:09:57,  1.40it/s]

  9800/15667 | 3.31/s | ETA ~30 min | checkpoint saved

sme_enrich:  64%|██████▍   | 10000/15667 [50:22<1:14:24,  1.27it/s]

  10000/15667 | 3.31/s | ETA ~29 min | checkpoint saved

sme_enrich:  65%|██████▌   | 10200/15667 [51:23<1:27:09,  1.05it/s]

  10200/15667 | 3.31/s | ETA ~28 min | checkpoint saved

sme_enrich:  66%|██████▋   | 10400/15667 [52:22<1:10:35,  1.24it/s]

  10400/15667 | 3.31/s | ETA ~27 min | checkpoint saved

sme_enrich:  68%|██████▊   | 10600/15667 [53:23<1:02:58,  1.34it/s]

  10600/15667 | 3.31/s | ETA ~26 min | checkpoint saved

sme_enrich:  69%|██████▉   | 10807/15667 [54:23<20:31,  3.95it/s]

  10800/15667 | 3.31/s | ETA ~25 min | checkpoint saved

sme_enrich:  70%|███████   | 11000/15667 [55:24<1:05:02,  1.20it/s]

  11000/15667 | 3.31/s | ETA ~24 min | checkpoint saved

sme_enrich:  71%|███████▏  | 11200/15667 [56:24<1:08:17,  1.09it/s]

  11200/15667 | 3.31/s | ETA ~23 min | checkpoint saved

sme_enrich:  73%|███████▎  | 11400/15667 [57:24<1:03:25,  1.12it/s]

  11400/15667 | 3.31/s | ETA ~21 min | checkpoint saved

sme_enrich:  74%|███████▍  | 11600/15667 [58:25<59:34,  1.14it/s]

  11600/15667 | 3.31/s | ETA ~20 min | checkpoint saved

sme_enrich:  75%|███████▌  | 11800/15667 [59:26<1:08:54,  1.07s/it]

  11800/15667 | 3.31/s | ETA ~19 min | checkpoint saved

sme_enrich:  77%|███████▋  | 12000/15667 [1:00:26<57:49,  1.06it/s]

  12000/15667 | 3.31/s | ETA ~18 min | checkpoint saved

sme_enrich:  78%|███████▊  | 12207/15667 [1:01:26<14:26,  4.00it/s]

  12200/15667 | 3.31/s | ETA ~17 min | checkpoint saved

sme_enrich:  79%|███████▉  | 12408/15667 [1:02:26<13:13,  4.11it/s]

  12400/15667 | 3.31/s | ETA ~16 min | checkpoint saved

sme_enrich:  80%|████████  | 12600/15667 [1:03:26<44:44,  1.14it/s]

  12600/15667 | 3.31/s | ETA ~15 min | checkpoint saved

sme_enrich:  82%|████████▏ | 12800/15667 [1:04:26<37:11,  1.28it/s]

  12800/15667 | 3.31/s | ETA ~14 min | checkpoint saved

sme_enrich:  83%|████████▎ | 13000/15667 [1:05:27<30:24,  1.46it/s]

  13000/15667 | 3.31/s | ETA ~13 min | checkpoint saved

sme_enrich:  84%|████████▍ | 13200/15667 [1:06:27<26:51,  1.53it/s]

  13200/15667 | 3.31/s | ETA ~12 min | checkpoint saved

sme_enrich:  86%|████████▌ | 13400/15667 [1:07:28<36:47,  1.03it/s]

  13400/15667 | 3.31/s | ETA ~11 min | checkpoint saved

sme_enrich:  87%|████████▋ | 13600/15667 [1:08:28<25:10,  1.37it/s]

  13600/15667 | 3.31/s | ETA ~10 min | checkpoint saved

sme_enrich:  88%|████████▊ | 13800/15667 [1:09:29<28:53,  1.08it/s]

  13800/15667 | 3.31/s | ETA ~9 min | checkpoint saved

sme_enrich:  89%|████████▉ | 14000/15667 [1:10:29<19:09,  1.45it/s]

  14000/15667 | 3.31/s | ETA ~8 min | checkpoint saved

sme_enrich:  91%|█████████ | 14200/15667 [1:11:30<19:06,  1.28it/s]

  14200/15667 | 3.31/s | ETA ~7 min | checkpoint saved

sme_enrich:  92%|█████████▏| 14400/15667 [1:12:31<16:41,  1.27it/s]

  14400/15667 | 3.31/s | ETA ~6 min | checkpoint saved

sme_enrich:  93%|█████████▎| 14606/15667 [1:13:31<04:38,  3.80it/s]

  14600/15667 | 3.31/s | ETA ~5 min | checkpoint saved

sme_enrich:  94%|█████████▍| 14800/15667 [1:14:32<12:04,  1.20it/s]

  14800/15667 | 3.31/s | ETA ~4 min | checkpoint saved

sme_enrich:  96%|█████████▌| 15000/15667 [1:15:33<09:19,  1.19it/s]

  15000/15667 | 3.31/s | ETA ~3 min | checkpoint saved

sme_enrich:  97%|█████████▋| 15200/15667 [1:16:33<06:05,  1.28it/s]

  15200/15667 | 3.31/s | ETA ~2 min | checkpoint saved

sme_enrich:  98%|█████████▊| 15400/15667 [1:17:34<03:36,  1.23it/s]

  15400/15667 | 3.31/s | ETA ~1 min | checkpoint saved

sme_enrich: 100%|█████████▉| 15600/15667 [1:18:34<00:47,  1.42it/s]

  15600/15667 | 3.31/s | ETA ~0 min | checkpoint saved

sme_enrich: 100%|██████████| 15667/15667 [1:18:52<00:00,  3.31it/s]

Saved -> company_data/companies.csv

,lloyds_customer,recent_charge_status,recent_charge_created_on,recent_psc_kind
2025-03-28,NaN,NaN,155.0,NaN
2025-03-31,NaN,NaN,118.0,NaN
2025-12-19,NaN,NaN,123.0,NaN
2026-05-29,NaN,NaN,123.0,NaN
False,451227.0,NaN,NaN,NaN
True,16126.0,NaN,NaN,NaN
corporate-entity-person-with-significant-control,NaN,NaN,NaN,36428.0
error,10.0,10.0,NaN,11.0
fully-satisfied,NaN,16710.0,NaN,NaN
individual-person-with-significant-control,NaN,NaN,NaN,412203.0
legal-person-person-with-significant-control,NaN,NaN,NaN,495.0
no_charges,NaN,381211.0,381211.0,NaN
no_psc,NaN,NaN,NaN,18218.0
outstanding,NaN,69396.0,NaN,NaN
part-satisfied,NaN,35.0,NaN,NaN
NaN,223474.0,223474.0,223474.0,223474.0

## Stage 4: full charge history → `charges_history.csv` (the panel's label source)

The panel needs **every charge with its date and lender**, not just the recent-charge summary:
- **label** — Lloyds-group charge `created_on` **after** cutoff T (within the horizon) → positive
- **existing-customer exclusion** — Lloyds-group charge `created_on` **≤ T** → dropped from that cutoff
- **feature** — count of **non-Lloyds** charges `created_on` ≤ T (prior secured borrowing; allowed, not leakage)

**Efficiency — this costs ~1.8k calls, not 13.5k (~87% skipped):**
1. Stage 3 already told us which companies have **no charges** (`recent_charge_status == 'no_charges'`, ~11.8k of 13.5k) → **zero API calls** for them.
2. Companies whose JSON was already persisted (by the updated Stage 3, or a previous Stage 4 run) → **zero calls**.
3. Only companies **with** charges and **no JSON on disk** are fetched — ~**1,790** one-time (≈ 9 min at ~6.7 req/s across 4 keys). Resumable/checkpointed like every other stage.

Then a **zero-call parse** turns all persisted JSONs into one tidy table — one row per charge:
`com_num · charge_code · created_on · delivered_on · satisfied_on · status · classification · persons_entitled · is_lloyds`
(`is_lloyds` uses Stage 3's `LLOYDS_RE` — the curated Lloyds-group entity list.)

Output → `company_data/charges_history.csv`. ⚠️ Run the **Stage 3 cell first** (defines `LLOYDS_RE`; fills `recent_charge_status` for new companies).

In [11]:
# --- Stage 4: full charge history -> charges_history.csv -------------------------
# One-time backfill for companies enriched BEFORE Stage 3 started persisting the
# charge JSONs, then a zero-call parse of every JSON into one tidy per-charge table.
# Requires the Stage 3 cell to have run (LLOYDS_RE, CHARGE_JSON_DIR, COMPANIES).
CHARGES_OUT = Path("company_data") / "charges_history.csv"

sme = pd.read_csv(COMPANIES, dtype=str, low_memory=False)
sme["is_sme"] = sme["is_sme"].astype(str).str.lower().eq("true")
if "n_charges" not in sme.columns:
    sme["n_charges"] = pd.NA


def _charge_file(cnum):
    return CHARGE_JSON_DIR / f"{str(cnum).strip()}_charges.json"


# --- who needs an API call? -------------------------------------------------------
# no_charges/not_found (from stage 3)  -> 0 calls, mark n_charges=0 directly
# JSON already on disk                 -> 0 calls (stage 3 persisted it, or a
#                                         previous stage-4 run did)
# everyone else WITH charges           -> the one-time backfill (~1.8k companies)
no_need   = sme["recent_charge_status"].isin(["no_charges", "not_found"])
unknown   = sme["recent_charge_status"].isna()          # stage 3 not run for these
have_json = sme["com_num"].map(lambda c: _charge_file(c).exists())

sme.loc[no_need & sme["n_charges"].isna(), "n_charges"] = "0"   # free: no call needed
# SAFETY: the table now holds non-SME companies too. Every todo selection MUST
# be masked by is_sme or this stage would spend ~154k calls enriching companies
# that were deliberately excluded from the population.
todo = sme.index[sme["is_sme"] & ~no_need & ~unknown & ~have_json]
if unknown.any():
    print(f"NOTE: {unknown.sum()} companies have no recent_charge_status yet — "
          "run Stage 3 first so they can be classified (skipped here).")
print(f"charge history: {int(no_need.sum())} skipped as no-charges (0 calls) | "
      f"{int((~no_need & have_json).sum())} already on disk (0 calls) | "
      f"{len(todo)} to fetch")


def fetch_charge_history(company_num):
    """Page /charges and persist the FULL item list to JSON. Returns n_charges."""
    cnum = str(company_num).strip()
    start, items = 0, []
    while True:
        r = ch_get(f"/company/{cnum}/charges",
                   params={"items_per_page": 100, "start_index": start})
        if r is None:
            return "error"
        if r.status_code == 404:
            break                                    # no charges registered
        if r.status_code != 200:
            return "error"
        data = r.json()
        page = data.get("items", [])
        items.extend(page)
        start += len(page)
        if not page or start >= data.get("total_count", 0):
            break
    _charge_file(cnum).write_text(json.dumps({"total_count": len(items),
                                              "items": items}))
    return str(len(items))


parallel_fill(sme, todo, fetch_charge_history, "n_charges", COMPANIES, desc="charges_hist")

# --- parse ALL persisted JSONs -> one row per charge (zero API calls) -------------
# Only companies Stage 3 says HAVE charges can contribute rows. The other ~255k have
# an empty JSON on disk, so skipping them avoids ~5x the filesystem work (the real
# cost here is 312k lookups in one folder, not the API).
_worth_parsing = ~sme["recent_charge_status"].isin(["no_charges", "not_found"])

rows = []
for cnum in sme.loc[_worth_parsing, "com_num"]:
    f = _charge_file(cnum)
    if not f.exists():
        continue
    for ch in json.loads(f.read_text()).get("items", []):
        lenders = " | ".join(p.get("name", "") for p in ch.get("persons_entitled", []))
        rows.append({
            "com_num":          cnum,
            "charge_code":      ch.get("charge_code") or ch.get("charge_number"),
            "created_on":       ch.get("created_on"),
            "delivered_on":     ch.get("delivered_on"),
            "satisfied_on":     ch.get("satisfied_on"),
            "status":           ch.get("status"),
            "classification":   (ch.get("classification") or {}).get("description"),
            "persons_entitled": lenders,
            "is_lloyds":        bool(LLOYDS_RE.search(lenders)),
        })
charges_hist = pd.DataFrame(rows)
charges_hist.to_csv(CHARGES_OUT, index=False)

# --- sanity report -----------------------------------------------------------------
n_cos = charges_hist["com_num"].nunique() if len(charges_hist) else 0
n_llo = int(charges_hist["is_lloyds"].sum()) if len(charges_hist) else 0
llo_cos = charges_hist.loc[charges_hist["is_lloyds"], "com_num"].nunique() if len(charges_hist) else 0
print(f"\ncharges_history: {len(charges_hist)} charges across {n_cos} companies "
      f"-> {CHARGES_OUT}")
print(f"  Lloyds-group charges: {n_llo} across {llo_cos} companies "
      f"(cf. lloyds_customer=True in the SME file: "
      f"{(sme['lloyds_customer'] == 'True').sum()})")
if len(charges_hist):
    print(f"  created_on range: {charges_hist['created_on'].min()} -> "
          f"{charges_hist['created_on'].max()}")
    print("  most common lenders:")
    print(charges_hist["persons_entitled"].value_counts().head(8).to_string())

NOTE: 223474 companies have no recent_charge_status yet — run Stage 3 first so they can be classified (skipped here).
charge history: 381211 skipped as no-charges (0 calls) | 86155 already on disk (0 calls) | 0 to fetch
0 to fetch (of 690837) — 4 keys x 8 workers

charges_hist: 0it [00:00, ?it/s]

Nothing to fetch — company_data/companies.csv left untouched.

charges_history: 326688 charges across 86148 companies -> company_data/charges_history.csv
  Lloyds-group charges: 44222 across 16128 companies (cf. lloyds_customer=True in the SME file: 16126)
  created_on range: 1903-12-09 -> 2026-08-13
  most common lenders:
persons_entitled
National Westminster Bank PLC          26534
Barclays Bank PLC                      22105
Lloyds Bank PLC                        14925
Hsbc Bank PLC                          10588
The Royal Bank of Scotland PLC         10390
The Mortgage Works (UK) PLC             9569
Together Commercial Finance Limited     8806
Paragon Bank PLC                        7431

## Stage 4b: rebuild `charges_history.csv` from the JSONs already on disk (ZERO API calls)

**Why this exists.** Stage 4 fetches charge JSONs *and* parses them into `charges_history.csv` in one go. If the company population grows after a parse, the CSV goes stale: the JSONs for the new firms are on disk, but they were never parsed in. As of the last check that gap was **10,188 firms (~32k charge rows), including 1,937 Lloyds customers** — i.e. ~19% of the label was missing.

This cell re-parses **every** `*_charges.json` on disk against the current SME file. No API calls, safe to run any time, and it is the cell to run after any population expansion.

In [12]:
# --- Stage 4b: rebuild charges_history.csv from disk (no API calls) --------------
# Parses every persisted charge JSON for companies in the CURRENT SME file.
# Run after any population expansion so the label source stays complete.
import json
import pandas as pd
from pathlib import Path

sme = pd.read_csv(COMPANIES, dtype=str, low_memory=False)
sme["is_sme"] = sme["is_sme"].astype(str).str.lower().eq("true")
before = pd.read_csv(CHARGES_OUT, dtype=str) if Path(CHARGES_OUT).exists() else pd.DataFrame()

# skip the ~255k companies Stage 3 marked as having no charges: their JSONs are
# empty, and touching 312k files in one folder is what makes this slow.
_worth_parsing = ~sme["recent_charge_status"].isin(["no_charges", "not_found"])
print(f"parsing {_worth_parsing.sum():,} of {len(sme):,} companies "
      f"(skipping {(~_worth_parsing).sum():,} with no charges)")

rows, missing_json = [], 0
for cnum in sme.loc[_worth_parsing, "com_num"]:
    f = _charge_file(cnum)
    if not f.exists():
        missing_json += 1
        continue
    for ch in json.loads(f.read_text()).get("items", []):
        lenders = " | ".join(p.get("name", "") for p in ch.get("persons_entitled", []))
        rows.append({
            "com_num":          cnum,
            "charge_code":      ch.get("charge_code") or ch.get("charge_number"),
            "created_on":       ch.get("created_on"),
            "delivered_on":     ch.get("delivered_on"),
            "satisfied_on":     ch.get("satisfied_on"),
            "status":           ch.get("status"),
            "classification":   (ch.get("classification") or {}).get("description"),
            "persons_entitled": lenders,
            "is_lloyds":        bool(LLOYDS_RE.search(lenders)),
        })

charges_hist = pd.DataFrame(rows)
charges_hist.to_csv(CHARGES_OUT, index=False)

# --- before/after report ----------------------------------------------------------
def _stats(df):
    if not len(df):
        return 0, 0, 0
    ll = df["is_lloyds"].astype(str).str.lower().eq("true")
    return len(df), df["com_num"].nunique(), df.loc[ll, "com_num"].nunique()

b_rows, b_firms, b_ll = _stats(before)
a_rows, a_firms, a_ll = _stats(charges_hist)
print(f"charges_history rebuilt -> {CHARGES_OUT}")
print(f"  rows          : {b_rows:>8,}  ->  {a_rows:>8,}   ({a_rows-b_rows:+,})")
print(f"  firms         : {b_firms:>8,}  ->  {a_firms:>8,}   ({a_firms-b_firms:+,})")
print(f"  Lloyds firms  : {b_ll:>8,}  ->  {a_ll:>8,}   ({a_ll-b_ll:+,})   <- the label")
print(f"  companies with no JSON on disk (never fetched): {missing_json:,}")

# cross-check against the Stage-3 flag; these two should now agree closely
flag = sme["lloyds_customer"].astype(str).eq("True").sum()
print(f"\n  Stage-3 lloyds_customer=True : {flag:,}")
print(f"  charges_history Lloyds firms : {a_ll:,}   (gap {flag - a_ll:+,})")

parsing 309,626 of 690,837 companies (skipping 381,211 with no charges)
charges_history rebuilt -> company_data/charges_history.csv
  rows          :  326,688  ->   326,688   (+0)
  firms         :   86,148  ->    86,148   (+0)
  Lloyds firms  :   16,128  ->    16,128   (+0)   <- the label
  companies with no JSON on disk (never fetched): 223,471

  Stage-3 lloyds_customer=True : 16,126
  charges_history Lloyds firms : 16,128   (gap -2)

## Stage 5: backfill panel fields — `date_of_creation` & co. (one-time)

Stage 1 now captures four **panel fields** from the profile call it already makes — but every company pulled *before* that change is missing them. This one-time backfill re-pulls the profile **only for SME rows missing `date_of_creation`**:

- `date_of_creation` — incorporation date → **`age@T`** (age at any cutoff = T − this date)
- `company_status` — active / dissolved / liquidation → drop non-active firms from lead lists
- `last_accounts_made_up_to` — most recent accounts date → accounts recency at T
- `next_accounts_due_on` — due date → punctuality / overdue-at-T

**Cost:** one `/company/{num}` call per legacy SME (~13.5k ≈ **34 min** at ~6.7 req/s across 4 keys) — one-time only. Resumable/checkpointed: interrupt any time and re-run; already-filled rows are never re-fetched, and **future runs cost ~0 calls** because Stage 1 captures these fields for every new company (Stage 2 carries them forward).

Writes into the SME file (`com_names_sme_test.csv`) in place — after this, the SME table + `charges_history.csv` (+ the GDELT `media_index`) are everything `build_panel()` needs.

In [13]:
# --- Stage 5: backfill panel fields from the profile (one-time, resumable) -------
# Only SME rows missing date_of_creation are fetched; new companies get these at
# Stage 1 for free, so this backfill shrinks to zero over time.
COMPANIES = Path("company_data") / "companies.csv"
PANEL_COLS = ["date_of_creation", "company_status",
              "last_accounts_made_up_to", "next_accounts_due_on"]

sme = pd.read_csv(COMPANIES, dtype=str, low_memory=False)
sme["is_sme"] = sme["is_sme"].astype(str).str.lower().eq("true")
for c in PANEL_COLS:
    if c not in sme.columns:
        sme[c] = pd.NA


def fetch_panel_fields(company_num):
    """(date_of_creation, company_status, last_accounts_made_up_to,
        next_accounts_due_on) from ONE profile call."""
    r = ch_get(f"/company/{str(company_num).strip()}")
    if r is None:              return ("error",) * 4
    if r.status_code == 404:   return ("not_found",) * 4
    if r.status_code != 200:   return ("error",) * 4
    j = r.json()
    acc = j.get("accounts", {})
    return (j.get("date_of_creation") or "unknown",
            j.get("company_status") or "unknown",
            acc.get("last_accounts", {}).get("made_up_to") or "none",
            acc.get("next_accounts", {}).get("due_on") or "none")


# SAFETY: the table now holds non-SME companies too — mask by is_sme or this
# stage would spend calls on companies excluded from the population.
todo = sme.index[sme["is_sme"] & sme["date_of_creation"].isna()]
parallel_fill(sme, todo, fetch_panel_fields, PANEL_COLS, COMPANIES, desc="panel_fields")

# --- sanity report ----------------------------------------------------------------
print("\npanel-field coverage:")
for c in PANEL_COLS:
    filled = sme[c].notna() & ~sme[c].isin(["error", "not_found"])
    print(f"  {c:26s} {int(filled.sum())}/{len(sme)}")
if sme["date_of_creation"].notna().any():
    ok = sme.loc[~sme["date_of_creation"].isin(["error", "not_found", "unknown"]),
                 "date_of_creation"]
    print(f"\n  incorporation dates: {ok.min()} -> {ok.max()}")
    print("  company_status:")
    print(sme["company_status"].value_counts(dropna=False).head(6).to_string())

0 to fetch (of 690837) — 4 keys x 8 workers

panel_fields: 0it [00:00, ?it/s]

Nothing to fetch — company_data/companies.csv left untouched.

panel-field coverage:
  date_of_creation           690809/690837
  company_status             690809/690837
  last_accounts_made_up_to   690809/690837
  next_accounts_due_on       690809/690837

  incorporation dates: 1856-09-25 -> 2026-05-31
  company_status:
company_status
active            690042
liquidation          552
receivership         121
administration        50
dissolved             36
error                 27

## Stage 6: full filing history → `filings_history.csv` (point-in-time feature source)

Mirrors Stage 4 (charges): one `/filing-history` call per company, persist the item list to JSON, then a zero-call parse into one tidy per-filing table. This is the raw source for the point-in-time **filing features** built in `GDELT.ipynb` Part 6c (accounts punctuality, staleness, count). Resumable + checkpointed via `parallel_fill`. **`SAMPLE_N` defaults to a small probe** — set it to `None` for the full ~304k pull.

In [14]:
# --- Stage 6: full filing history -> filings_history.csv --------------------------
import numpy as np
# One /filing-history call per company (paged), persisted to JSON, then parsed to a
# per-filing table. Requires the client cell (ch_get, parallel_fill) + COMPANIES.
FILING_JSON_DIR = CHARGE_JSON_DIR                       # reuse the same json folder
FILINGS_OUT     = Path("company_data") / "filings_history.csv"

# PULL MODE — three settings, in the order you should use them:
#
#   "stratified"  EVERY known Lloyds customer + N_CONTROLS random non-customers.
#                 ~76 min for 30k companies. This is the one to run FIRST.
#                 Why: all the information about "what predicts conversion" lives in
#                 the ~10k customers. A plain first-N or random probe of a few hundred
#                 lands ~16 customers, which can only detect a ~35 percentage-point
#                 effect — useless. Taking every customer gives +-0.5% precision, so a
#                 real effect is unmissable. And the pull is NOT throwaway: these are
#                 exactly the rows a case-control model trains on (same design as
#                 data_conditional.ipynb).
#
#   "full"        all ~312k companies, ~13h. Needed only to SCORE the live lead list,
#                 not to decide whether a feature works. Resumable — it skips anyone
#                 already on disk, so "stratified" then "full" costs nothing extra.
#
#   "first_n"     legacy first-N-rows behaviour. Do NOT use for evaluation: the SME
#                 file is name-sorted, so the first rows are ~1% customers vs 3.3%
#                 overall (lots of numeric-named RTM shells that never borrow).
PULL_MODE   = "stratified"
N_CONTROLS  = 20000        # non-customers sampled alongside every customer
SAMPLE_N    = 500          # only used when PULL_MODE == "first_n"
SEED        = 42

sme = pd.read_csv(COMPANIES, dtype=str, low_memory=False)
sme["is_sme"] = sme["is_sme"].astype(str).str.lower().eq("true")
if "n_filings" not in sme.columns:
    sme["n_filings"] = pd.NA


def _filing_file(cnum):
    return FILING_JSON_DIR / f"{str(cnum).strip()}_filings.json"


def fetch_filing_history(company_num):
    """Page /filing-history and persist the FULL item list to JSON. Returns n_filings."""
    cnum = str(company_num).strip()
    start, items = 0, []
    while True:
        r = ch_get(f"/company/{cnum}/filing-history",
                   params={"items_per_page": 100, "start_index": start})
        if r is None:
            return "error"
        if r.status_code == 404:
            break                                      # no filing history
        if r.status_code != 200:
            return "error"
        data = r.json()
        page = data.get("items", [])
        items.extend(page)
        start += len(page)
        if not page or start >= data.get("total_count", 0):
            break
    _filing_file(cnum).write_text(json.dumps({"total_count": len(items), "items": items}))
    return str(len(items))


# who needs a call? anyone without a persisted JSON and without n_filings yet
have_json = sme["com_num"].map(lambda c: _filing_file(c).exists())
# SAFETY: the table now holds non-SME companies too. Every todo selection MUST
# be masked by is_sme or this stage would spend ~154k calls enriching companies
# that were deliberately excluded from the population.
todo = sme.index[sme["is_sme"] & sme["n_filings"].isna() & ~have_json]

_is_cust = sme["lloyds_customer"].astype(str).str.lower().eq("true")

if PULL_MODE == "stratified":
    _rng   = np.random.default_rng(SEED)
    _pos   = sme.index[_is_cust]                                  # every known customer
    _negs  = sme.index[~_is_cust]
    _neg   = pd.Index(_rng.choice(_negs, size=min(N_CONTROLS, len(_negs)), replace=False))
    todo   = todo.intersection(_pos.union(_neg))
    _npos  = int(_is_cust.loc[todo].sum())
    print(f"STRATIFIED: {len(todo):,} companies to fetch "
          f"({_npos:,} Lloyds customers + {len(todo)-_npos:,} controls) "
          f"~{len(todo) / (len(_LANES) / _MIN_INTERVAL) / 60:.0f} min")
elif PULL_MODE == "full":
    print(f"FULL PULL: {len(todo):,} companies to fetch "
          f"(~{len(todo) / (len(_LANES) / _MIN_INTERVAL) / 3600:.1f}h, resumable).")
elif PULL_MODE == "first_n":
    todo = todo[:SAMPLE_N]
    print(f"FIRST-N (biased — evaluation-unsafe): {len(todo):,} companies.")
else:
    raise ValueError("PULL_MODE must be 'stratified', 'full' or 'first_n'")

parallel_fill(sme, todo, fetch_filing_history, "n_filings", COMPANIES, desc="filing_hist")

# --- parse ALL persisted filing JSONs -> one row per filing (zero API calls) ------
rows = []
for cnum in sme.loc[sme["is_sme"], "com_num"]:
    f = _filing_file(cnum)
    if not f.exists():
        continue
    for it in json.loads(f.read_text()).get("items", []):
        dv = it.get("description_values") or {}
        rows.append({
            "com_num":      cnum,
            "category":     it.get("category"),
            "type":         it.get("type"),
            "date":         it.get("date"),                       # date filed/received
            "made_up_date": dv.get("made_up_date") or it.get("action_date"),
            "paper_filed":  bool(it.get("paper_filed")),
            "doc_metadata": (it.get("links") or {}).get("document_metadata"),  # for Phase B iXBRL
        })
filings_hist = pd.DataFrame(rows)
filings_hist.to_csv(FILINGS_OUT, index=False)

# --- sanity report -----------------------------------------------------------------
n_cos = filings_hist["com_num"].nunique() if len(filings_hist) else 0
acc = (filings_hist[filings_hist["category"] == "accounts"]
       if len(filings_hist) else filings_hist)
print(f"\nfilings_history: {len(filings_hist)} filings across {n_cos} companies -> {FILINGS_OUT}")
print(f"  accounts filings: {len(acc)} across "
      f"{acc['com_num'].nunique() if len(acc) else 0} companies")
if len(filings_hist):
    print("  categories:")
    print(filings_hist["category"].value_counts().head(8).to_string())

# --- is the pull informative yet? (customers vs controls actually fetched) --------
_pulled = set(filings_hist["com_num"]) if len(filings_hist) else set()
_have   = sme[sme["com_num"].isin(_pulled)]
_hp     = _have["lloyds_customer"].astype(str).str.lower().eq("true").sum()
print(f"\ncoverage so far: {len(_have):,} companies with filing history "
      f"({_hp:,} Lloyds customers, {len(_have)-_hp:,} controls)")
if _hp < 500:
    print("  ⚠️  under ~500 customers: too few to judge a feature "
          "(see the PULL_MODE notes). Run PULL_MODE='stratified'.")
else:
    import math
    _se = math.sqrt(0.3 * 0.7 / _hp)
    print(f"  precision on a ~30%-prevalence feature: +-{_se*100:.1f}% "
          f"-> can detect gaps larger than ~{3*_se*100:.1f} percentage points")

STRATIFIED: 16,684 companies to fetch (3,725 Lloyds customers + 12,959 controls) ~42 min
16684 to fetch (of 690837) — 4 keys x 8 workers

filing_hist:   1%|          | 200/16684 [00:34<1:19:57,  3.44it/s]

  200/16684 | 5.78/s | ETA ~47 min | checkpoint saved

filing_hist:   2%|▏         | 400/16684 [01:08<1:47:33,  2.52it/s]

  400/16684 | 5.84/s | ETA ~46 min | checkpoint saved

filing_hist:   4%|▎         | 613/16684 [01:41<29:58,  8.94it/s]

  600/16684 | 5.93/s | ETA ~45 min | checkpoint saved

filing_hist:   5%|▍         | 815/16684 [02:12<30:27,  8.68it/s]

  800/16684 | 6.05/s | ETA ~44 min | checkpoint saved

filing_hist:   6%|▌         | 1000/16684 [02:43<1:44:06,  2.51it/s]

  1000/16684 | 6.11/s | ETA ~43 min | checkpoint saved

filing_hist:   7%|▋         | 1211/16684 [03:16<35:38,  7.23it/s]

  1200/16684 | 6.11/s | ETA ~42 min | checkpoint saved

filing_hist:   8%|▊         | 1400/16684 [03:48<1:21:34,  3.12it/s]

  1400/16684 | 6.12/s | ETA ~42 min | checkpoint saved

filing_hist:  10%|▉         | 1600/16684 [04:18<1:06:44,  3.77it/s]

  1600/16684 | 6.18/s | ETA ~41 min | checkpoint saved

filing_hist:  11%|█         | 1800/16684 [04:50<1:40:59,  2.46it/s]

  1800/16684 | 6.18/s | ETA ~40 min | checkpoint saved

filing_hist:  12%|█▏        | 2013/16684 [05:21<27:57,  8.75it/s]

  2000/16684 | 6.21/s | ETA ~39 min | checkpoint saved

filing_hist:  13%|█▎        | 2200/16684 [05:53<1:51:56,  2.16it/s]

  2200/16684 | 6.22/s | ETA ~39 min | checkpoint saved

filing_hist:  14%|█▍        | 2401/16684 [06:24<1:22:44,  2.88it/s]

  2400/16684 | 6.24/s | ETA ~38 min | checkpoint saved

filing_hist:  16%|█▌        | 2600/16684 [06:55<1:23:01,  2.83it/s]

  2600/16684 | 6.25/s | ETA ~38 min | checkpoint saved

filing_hist:  17%|█▋        | 2814/16684 [07:26<27:24,  8.43it/s]

  2800/16684 | 6.26/s | ETA ~37 min | checkpoint saved

filing_hist:  18%|█▊        | 3000/16684 [07:57<1:40:06,  2.28it/s]

  3000/16684 | 6.27/s | ETA ~36 min | checkpoint saved

filing_hist:  19%|█▉        | 3200/16684 [08:28<1:33:42,  2.40it/s]

  3200/16684 | 6.29/s | ETA ~36 min | checkpoint saved

filing_hist:  20%|██        | 3400/16684 [09:01<1:44:53,  2.11it/s]

  3400/16684 | 6.28/s | ETA ~35 min | checkpoint saved

filing_hist:  22%|██▏       | 3613/16684 [09:31<24:53,  8.75it/s]

  3600/16684 | 6.29/s | ETA ~35 min | checkpoint saved

filing_hist:  23%|██▎       | 3801/16684 [10:03<1:32:15,  2.33it/s]

  3800/16684 | 6.30/s | ETA ~34 min | checkpoint saved

filing_hist:  24%|██▍       | 4000/16684 [10:34<1:24:48,  2.49it/s]

  4000/16684 | 6.30/s | ETA ~34 min | checkpoint saved

filing_hist:  25%|██▌       | 4200/16684 [11:05<1:13:07,  2.85it/s]

  4200/16684 | 6.31/s | ETA ~33 min | checkpoint saved

filing_hist:  26%|██▋       | 4400/16684 [11:36<1:10:37,  2.90it/s]

  4400/16684 | 6.31/s | ETA ~32 min | checkpoint saved

filing_hist:  28%|██▊       | 4600/16684 [12:07<1:08:55,  2.92it/s]

  4600/16684 | 6.32/s | ETA ~32 min | checkpoint saved

filing_hist:  29%|██▉       | 4800/16684 [12:38<1:10:39,  2.80it/s]

  4800/16684 | 6.32/s | ETA ~31 min | checkpoint saved

filing_hist:  30%|██▉       | 5001/16684 [13:09<1:14:44,  2.61it/s]

  5000/16684 | 6.33/s | ETA ~31 min | checkpoint saved

filing_hist:  31%|███▏      | 5214/16684 [13:40<24:05,  7.93it/s]

  5200/16684 | 6.34/s | ETA ~30 min | checkpoint saved

filing_hist:  32%|███▏      | 5400/16684 [14:11<1:25:10,  2.21it/s]

  5400/16684 | 6.34/s | ETA ~30 min | checkpoint saved

filing_hist:  34%|███▎      | 5616/16684 [14:43<19:50,  9.30it/s]

  5600/16684 | 6.34/s | ETA ~29 min | checkpoint saved

filing_hist:  35%|███▍      | 5800/16684 [15:14<1:03:41,  2.85it/s]

  5800/16684 | 6.34/s | ETA ~29 min | checkpoint saved

filing_hist:  36%|███▌      | 6000/16684 [15:46<1:08:51,  2.59it/s]

  6000/16684 | 6.33/s | ETA ~28 min | checkpoint saved

filing_hist:  37%|███▋      | 6200/16684 [16:19<1:08:08,  2.56it/s]

  6200/16684 | 6.33/s | ETA ~28 min | checkpoint saved

filing_hist:  38%|███▊      | 6400/16684 [16:51<1:05:58,  2.60it/s]

  6400/16684 | 6.33/s | ETA ~27 min | checkpoint saved

filing_hist:  40%|███▉      | 6614/16684 [17:22<19:40,  8.53it/s]

  6600/16684 | 6.33/s | ETA ~27 min | checkpoint saved

filing_hist:  41%|████      | 6800/16684 [17:53<49:20,  3.34it/s]

  6800/16684 | 6.33/s | ETA ~26 min | checkpoint saved

filing_hist:  42%|████▏     | 7000/16684 [18:24<52:25,  3.08it/s]

  7000/16684 | 6.34/s | ETA ~25 min | checkpoint saved

filing_hist:  43%|████▎     | 7200/16684 [18:55<43:15,  3.65it/s]

  7200/16684 | 6.34/s | ETA ~25 min | checkpoint saved

filing_hist:  44%|████▍     | 7401/16684 [19:27<1:02:57,  2.46it/s]

  7400/16684 | 6.34/s | ETA ~24 min | checkpoint saved

filing_hist:  46%|████▌     | 7600/16684 [19:58<58:52,  2.57it/s]

  7600/16684 | 6.34/s | ETA ~24 min | checkpoint saved

filing_hist:  47%|████▋     | 7800/16684 [20:30<45:55,  3.22it/s]

  7800/16684 | 6.34/s | ETA ~23 min | checkpoint saved

filing_hist:  48%|████▊     | 8000/16684 [21:01<58:28,  2.48it/s]

  8000/16684 | 6.34/s | ETA ~23 min | checkpoint saved

filing_hist:  49%|████▉     | 8200/16684 [21:33<1:14:46,  1.89it/s]

  8200/16684 | 6.34/s | ETA ~22 min | checkpoint saved

filing_hist:  50%|█████     | 8400/16684 [22:07<51:54,  2.66it/s]

  8400/16684 | 6.33/s | ETA ~22 min | checkpoint saved

filing_hist:  52%|█████▏    | 8600/16684 [22:40<48:41,  2.77it/s]

  8600/16684 | 6.32/s | ETA ~21 min | checkpoint saved

filing_hist:  53%|█████▎    | 8814/16684 [23:13<15:48,  8.30it/s]

  8800/16684 | 6.32/s | ETA ~21 min | checkpoint saved

filing_hist:  54%|█████▍    | 9000/16684 [23:44<1:02:38,  2.04it/s]

  9000/16684 | 6.32/s | ETA ~20 min | checkpoint saved

filing_hist:  55%|█████▌    | 9214/16684 [24:16<15:34,  7.99it/s]

  9200/16684 | 6.32/s | ETA ~20 min | checkpoint saved

filing_hist:  56%|█████▋    | 9415/16684 [24:48<14:14,  8.51it/s]

  9400/16684 | 6.31/s | ETA ~19 min | checkpoint saved

filing_hist:  58%|█████▊    | 9614/16684 [25:20<13:12,  8.92it/s]

  9600/16684 | 6.31/s | ETA ~19 min | checkpoint saved

filing_hist:  59%|█████▊    | 9800/16684 [25:52<44:35,  2.57it/s]

  9800/16684 | 6.31/s | ETA ~18 min | checkpoint saved

filing_hist:  60%|██████    | 10013/16684 [26:23<12:36,  8.82it/s]

  10000/16684 | 6.31/s | ETA ~18 min | checkpoint saved

filing_hist:  61%|██████    | 10200/16684 [27:00<45:41,  2.36it/s]

  10200/16684 | 6.29/s | ETA ~17 min | checkpoint saved

filing_hist:  62%|██████▏   | 10400/16684 [27:36<47:33,  2.20it/s]

  10400/16684 | 6.28/s | ETA ~17 min | checkpoint saved

filing_hist:  64%|██████▎   | 10600/16684 [28:11<53:37,  1.89it/s]

  10600/16684 | 6.26/s | ETA ~16 min | checkpoint saved

filing_hist:  65%|██████▍   | 10800/16684 [28:48<38:29,  2.55it/s]

  10800/16684 | 6.25/s | ETA ~16 min | checkpoint saved

filing_hist:  66%|██████▌   | 11000/16684 [29:25<35:00,  2.71it/s]

  11000/16684 | 6.23/s | ETA ~15 min | checkpoint saved

filing_hist:  67%|██████▋   | 11200/16684 [30:00<28:37,  3.19it/s]

  11200/16684 | 6.22/s | ETA ~15 min | checkpoint saved

filing_hist:  68%|██████▊   | 11400/16684 [30:36<32:54,  2.68it/s]

  11400/16684 | 6.21/s | ETA ~14 min | checkpoint saved

filing_hist:  70%|██████▉   | 11600/16684 [31:13<30:22,  2.79it/s]

  11600/16684 | 6.19/s | ETA ~14 min | checkpoint saved

filing_hist:  71%|███████   | 11800/16684 [31:50<36:32,  2.23it/s]

  11800/16684 | 6.17/s | ETA ~13 min | checkpoint saved

filing_hist:  72%|███████▏  | 12000/16684 [32:28<35:33,  2.20it/s]

  12000/16684 | 6.16/s | ETA ~13 min | checkpoint saved

filing_hist:  73%|███████▎  | 12200/16684 [33:03<28:47,  2.60it/s]

  12200/16684 | 6.15/s | ETA ~12 min | checkpoint saved

filing_hist:  74%|███████▍  | 12400/16684 [33:39<24:25,  2.92it/s]

  12400/16684 | 6.14/s | ETA ~12 min | checkpoint saved

filing_hist:  76%|███████▌  | 12600/16684 [34:15<32:24,  2.10it/s]

  12600/16684 | 6.13/s | ETA ~11 min | checkpoint saved

filing_hist:  77%|███████▋  | 12800/16684 [34:52<27:51,  2.32it/s]

  12800/16684 | 6.12/s | ETA ~11 min | checkpoint saved

filing_hist:  78%|███████▊  | 13000/16684 [35:31<26:51,  2.29it/s]

  13000/16684 | 6.10/s | ETA ~10 min | checkpoint saved

filing_hist:  79%|███████▉  | 13200/16684 [36:09<24:04,  2.41it/s]

  13200/16684 | 6.08/s | ETA ~10 min | checkpoint saved

filing_hist:  80%|████████  | 13400/16684 [36:45<25:25,  2.15it/s]

  13400/16684 | 6.07/s | ETA ~9 min | checkpoint saved

filing_hist:  82%|████████▏ | 13600/16684 [37:22<17:22,  2.96it/s]

  13600/16684 | 6.06/s | ETA ~8 min | checkpoint saved

filing_hist:  83%|████████▎ | 13800/16684 [37:59<19:32,  2.46it/s]

  13800/16684 | 6.05/s | ETA ~8 min | checkpoint saved

filing_hist:  84%|████████▍ | 14000/16684 [38:38<24:06,  1.86it/s]

  14000/16684 | 6.04/s | ETA ~7 min | checkpoint saved

filing_hist:  85%|████████▌ | 14200/16684 [39:13<15:24,  2.69it/s]

  14200/16684 | 6.03/s | ETA ~7 min | checkpoint saved

filing_hist:  86%|████████▋ | 14400/16684 [39:50<18:02,  2.11it/s]

  14400/16684 | 6.02/s | ETA ~6 min | checkpoint saved

filing_hist:  88%|████████▊ | 14600/16684 [40:29<12:52,  2.70it/s]

  14600/16684 | 6.01/s | ETA ~6 min | checkpoint saved

filing_hist:  89%|████████▊ | 14800/16684 [41:09<15:29,  2.03it/s]

  14800/16684 | 5.99/s | ETA ~5 min | checkpoint saved

filing_hist:  90%|████████▉ | 15000/16684 [41:45<10:22,  2.70it/s]

  15000/16684 | 5.99/s | ETA ~5 min | checkpoint saved

filing_hist:  91%|█████████ | 15200/16684 [42:21<09:58,  2.48it/s]

  15200/16684 | 5.98/s | ETA ~4 min | checkpoint saved

filing_hist:  92%|█████████▏| 15400/16684 [42:54<09:13,  2.32it/s]

  15400/16684 | 5.98/s | ETA ~4 min | checkpoint saved

filing_hist:  94%|█████████▎| 15600/16684 [43:28<07:19,  2.46it/s]

  15600/16684 | 5.98/s | ETA ~3 min | checkpoint saved

filing_hist:  95%|█████████▍| 15800/16684 [44:06<07:21,  2.00it/s]

  15800/16684 | 5.97/s | ETA ~2 min | checkpoint saved

filing_hist:  96%|█████████▌| 16000/16684 [44:42<05:27,  2.09it/s]

  16000/16684 | 5.96/s | ETA ~2 min | checkpoint saved

filing_hist:  97%|█████████▋| 16200/16684 [45:18<02:58,  2.71it/s]

  16200/16684 | 5.96/s | ETA ~1 min | checkpoint saved

filing_hist:  98%|█████████▊| 16400/16684 [45:56<02:08,  2.21it/s]

  16400/16684 | 5.95/s | ETA ~1 min | checkpoint saved

filing_hist:  99%|█████████▉| 16600/16684 [46:33<00:32,  2.56it/s]

  16600/16684 | 5.94/s | ETA ~0 min | checkpoint saved

filing_hist: 100%|██████████| 16684/16684 [46:47<00:00,  5.94it/s]

Saved -> company_data/companies.csv

filings_history: 2177512 filings across 42866 companies -> company_data/filings_history.csv
  accounts filings: 653629 across 42857 companies
  categories:
category
accounts                            653629
confirmation-statement              347706
officers                            347241
annual-return                       307717
mortgage                            166091
address                              90981
persons-with-significant-control     79508
incorporation                        48170

coverage so far: 42,866 companies with filing history (16,126 Lloyds customers, 26,740 controls)
  precision on a ~30%-prevalence feature: +-0.4% -> can detect gaps larger than ~1.1 percentage points

## Normalise types for analysis

Load a typed view (`sme_typed`) with `lloyds_customer` as a real boolean, so filtering and `== True` work. The CSV on disk stays uniform text.

In [15]:
# --- Analysis-ready load: consistent dtypes & safe comparisons -----------------
# The CSV stores everything as text (uniform "True"/"False"/sentinels). This loads
# a typed view where the boolean flags become real nullable booleans, so you can do
# `sme_typed[sme_typed.lloyds_customer]` or `== True`. Non True/False values
# (e.g. 'error') become <NA> and are reported so nothing is hidden.
COMPANIES = Path("company_data") / "companies.csv"
_all_typed = pd.read_csv(COMPANIES, dtype=str, low_memory=False)

# The table holds non-SME companies too (the do-not-re-pull cache), so narrow to the
# modelling population — `sme_typed` should mean what its name says.
_is_sme   = _all_typed["is_sme"].astype(str).str.lower().eq("true")
sme_typed = _all_typed[_is_sme].copy()
print(f"loaded {len(_all_typed):,} rows -> {len(sme_typed):,} is_sme rows "
      f"({int((~_is_sme).sum()):,} non-SME cached rows held back)")

bool_map = {"True": True, "False": False}
for col in ("lloyds_customer", "accounts_overdue"):
    if col in sme_typed.columns:
        odd = sme_typed.loc[sme_typed[col].notna() & ~sme_typed[col].isin(bool_map), col]
        if len(odd):
            print(f"Non True/False {col} values -> <NA>:")
            print(odd.value_counts().to_string(), "\n")
        sme_typed[col] = sme_typed[col].map(bool_map).astype("boolean")
        print(f"{col}:")
        print(sme_typed[col].value_counts(dropna=False).to_string(), "\n")

for col in ("recent_psc_kind", "recent_charge_status"):
    if col in sme_typed.columns:
        print(f"{col}:")
        print(sme_typed[col].value_counts(dropna=False).to_string(), "\n")

# `sme_typed` is analysis-ready (e.g. sme_typed[sme_typed.lloyds_customer]).
# The CSV on disk stays canonical text.
sme_typed.head()

loaded 690,837 rows -> 467,363 is_sme rows (223,474 non-SME cached rows held back)
Non True/False lloyds_customer values -> <NA>:
lloyds_customer
error    10

lloyds_customer:
lloyds_customer
False    451227
True      16126
<NA>         10

Non True/False accounts_overdue values -> <NA>:
accounts_overdue
unknown    15

accounts_overdue:
accounts_overdue
False    460296
True       7052
<NA>         15

recent_psc_kind:
recent_psc_kind
individual-person-with-significant-control          412203
corporate-entity-person-with-significant-control     36428
no_psc                                               18218
legal-person-person-with-significant-control           495
error                                                   11
super-secure-person-with-significant-control             8

recent_charge_status:
recent_charge_status
no_charges         381211
outstanding         69396
fully-satisfied     16710
part-satisfied         35
error                  10
satisfied               1

,com_num,name,sic_code,account_type,is_sme,accounts_overdue,date_of_creation,company_status,last_accounts_made_up_to,next_accounts_due_on,...,com_name,lloyds_customer,recent_psc_kind,recent_charge_status,recent_charge_created_on,n_charges,n_filings,region,town_api,Unnamed: 0
12,13172868,369 TECHNICAL LTD,28302,total-exemption-full,True,False,2021-02-02,active,2025-02-28,2026-11-30,...,NaN,False,individual-person-with-significant-control,no_charges,no_charges,0,10,Wales,NaN,NaN
15,07852962,369 UPLAND ROAD RTM COMPANY LIMITED,98000,micro-entity,True,False,2011-11-18,active,2025-09-28,2027-06-28,...,NaN,False,no_psc,no_charges,no_charges,0,45,London,NaN,NaN
16,14568066,369 VORTEX LIMITED,64209,micro-entity,True,False,2023-01-03,active,2026-01-31,2027-10-31,...,NaN,False,individual-person-with-significant-control,no_charges,no_charges,0,7,East Midlands,NaN,NaN
17,15623849,369 WATCH PARTS LTD,47990,total-exemption-full,True,False,2024-04-07,active,2025-04-30,2027-01-31,...,NaN,False,individual-person-with-significant-control,no_charges,no_charges,0,4,London,NaN,NaN
20,16023853,369MULTI LTD,47520,micro-entity,True,False,2024-10-17,active,2025-10-31,2027-07-31,...,NaN,False,individual-person-with-significant-control,no_charges,no_charges,0,5,North West,NaN,NaN

## Repair com_num leading zeros

Realign `com_num` in `com_names_sme.csv` to the canonical values in `company_raw/` (fixes leading zeros dropped by Excel, e.g. `5914136` → `05914136`). Idempotent — run it any time, especially after opening/saving the CSV in a spreadsheet.

In [16]:
# --- Repair com_num: realign leading zeros to the raw originals ------------------
# UK company numbers keep leading zeros (e.g. 05914136). Opening the CSV in Excel
# can silently drop them (05914136 -> 5914136, or float-ify to 5914136.0). This
# remaps com_num back to the canonical values in company_raw/. Idempotent:
# reports 0 changed when the file is already aligned.
RAW_DIR = Path("company_data") / "company_raw"
COMPANIES = Path("company_data") / "companies.csv"


def _norm(x):
    """Collapse a com_num to a match key: drop a stray '.0', then leading zeros."""
    x = str(x).strip()
    if x.endswith(".0"):
        x = x[:-2]
    return x.lstrip("0")


# canonical map: normalized form -> original com_num (from the raw files)
raw = pd.concat([pd.read_csv(f, dtype=str) for f in sorted(RAW_DIR.glob("*.csv"))],
                ignore_index=True).drop_duplicates("com_num")
canon = {_norm(c): c for c in raw["com_num"]}

sme = pd.read_csv(COMPANIES, dtype=str)
before = sme["com_num"].copy()
sme["com_num"] = sme["com_num"].map(lambda x: canon.get(_norm(x), str(x).strip()))

changed = int((before != sme["com_num"]).sum())
unmatched = sme.loc[~sme["com_num"].isin(set(raw["com_num"])), "com_num"]
sme.to_csv(COMPANIES, index=False)
print(f"Aligned com_num -> {COMPANIES}")
print(f"  rows changed: {changed}")
print(f"  not matching any raw com_num: {len(unmatched)}")
if len(unmatched):
    print("  examples:", unmatched.head(5).tolist())

Aligned com_num -> company_data/companies.csv
  rows changed: 1
  not matching any raw com_num: 541878
  examples: ['06369946', '06381193', '07218758', '07806564', '08461200']