In [52]:
import requests
import os
import json
import pandas as pd
from dotenv import load_dotenv, dotenv_values
from requests.exceptions import HTTPError, ConnectionError, Timeout, RequestException
from pathlib import Path

In [67]:
load_dotenv(Path.cwd().parent / ".env")

True

In [68]:
URL_BASE = "https://api.company-information.service.gov.uk"
URL_META_DATA = "https://document-api.company-information.service.gov.uk/document"
TIMEOUT = 10  # seconds

In [69]:
#Company House

def get(endpoint, params=None, headers=None):
    url = f"{URL_BASE}/{endpoint}"
    response = requests.get(
        url,
        auth=(os.getenv("CH_API"),""),
        headers=headers,
        params=params,
        timeout=TIMEOUT
        )
    response.raise_for_status()
    print(response.status_code)
    return response.json()

def get_meta_data(endpoint, params=None, headers=None):
    url = f"{URL_META_DATA}/{endpoint}"
    response = requests.get(
        url,
        auth=(os.getenv("CH_API"),""),
        headers=headers,
        params=params,
        timeout=TIMEOUT
        )
    response.raise_for_status()
    return response

In [78]:
company_number = "00002065"

profile = get(f"/company/{company_number}")
profile

200

{'accounts': {'accounting_reference_date': {'day': '31', 'month': '12'},
  'last_accounts': {'made_up_to': '2025-12-31',
   'period_end_on': '2025-12-31',
   'period_start_on': '2025-01-01',
   'type': 'group'},
  'next_accounts': {'due_on': '2027-06-30',
   'overdue': False,
   'period_end_on': '2026-12-31',
   'period_start_on': '2026-01-01'},
  'next_due': '2027-06-30',
  'next_made_up_to': '2026-12-31',
  'overdue': False},
 'can_file': True,
 'company_name': 'LLOYDS BANK PLC',
 'company_number': '00002065',
 'company_status': 'active',
 'confirmation_statement': {'last_made_up_to': '2026-05-06',
  'next_due': '2027-05-20',
  'next_made_up_to': '2027-05-06',
  'overdue': False},
 'date_of_creation': '1865-04-20',
 'etag': '8259055527962f7d8a7133c1d55c10b900e50b46',
 'has_charges': False,
 'has_insolvency_history': False,
 'jurisdiction': 'england-wales',
 'last_full_members_list_date': '2016-05-09',
 'links': {'persons_with_significant_control': '/company/00002065/persons-with-significant-control',
  'self': '/company/00002065',
  'charges': '/company/00002065/charges',
  'filing_history': '/company/00002065/filing-history',
  'officers': '/company/00002065/officers'},
 'previous_company_names': [{'ceased_on': '2013-09-23',
   'effective_from': '1999-06-28',
   'name': 'LLOYDS TSB BANK PLC'},
  {'ceased_on': '1999-06-28',
   'effective_from': '1982-02-01',
   'name': 'LLOYDS BANK PLC'},
  {'ceased_on': '1982-02-01',
   'effective_from': '1889-04-05',
   'name': 'LLOYDS BANK LIMITED'},
  {'ceased_on': '1889-04-05',
   'effective_from': '1884-04-07',
   'name': 'LLOYDS, BARNETTS AND BOSANQUETS BANK LIMITED'},
  {'ceased_on': '1884-04-07',
   'effective_from': '1865-04-20',
   'name': 'LLOYDS BANKING COMPANY LIMITED'}],
 'registered_office_address': {'address_line_1': '25 Gresham Street',
  'locality': 'London',
  'postal_code': 'EC2V 7HN'},
 'registered_office_is_in_dispute': False,
 'sic_codes': ['64191'],
 'type': 'plc',
 'undeliverable_registered_office_address': False,
 'has_super_secure_pscs': False}

In [75]:
profile["company_number"]

'12247029'

In [76]:
# Filling History
data = get(f"/company/{company_number}/filing-history")

for i in data["items"]:
    print(i)

200
{'transaction_id': 'MzMxNjgwODI3M2FkaXF6a2N4', 'type': 'GAZ2(A)', 'date': '2021-10-19', 'category': 'gazette', 'description': 'gazette-dissolved-voluntary', 'pages': 1, 'paper_filed': True, 'links': {'self': '/company/12247029/filing-history/MzMxNjgwODI3M2FkaXF6a2N4', 'document_metadata': 'https://document-api.company-information.service.gov.uk/document/hfrP57D4zw2WcPApqsHv14z-YaNiNrUz3pKeiy2E6Qw'}}
{'transaction_id': 'MzMwODU4NjY3MWFkaXF6a2N4', 'type': 'GAZ1(A)', 'date': '2021-08-03', 'category': 'gazette', 'description': 'gazette-notice-voluntary', 'pages': 1, 'paper_filed': True, 'links': {'self': '/company/12247029/filing-history/MzMwODU4NjY3MWFkaXF6a2N4', 'document_metadata': 'https://document-api.company-information.service.gov.uk/document/mAO6sDGWhHbnCoYUjZsnhPqHkYvSHgCbDVYuDfoX1Vg'}}
{'transaction_id': 'MzMwODU4NjAwM2FkaXF6a2N4', 'barcode': 'XA9DE1BS', 'type': 'DS01', 'date': '2021-07-23', 'category': 'dissolution', 'description': 'dissolution-application-strike-off-company', 'pages': 1, 'links': {'self': '/company/12247029/filing-history/MzMwODU4NjAwM2FkaXF6a2N4', 'document_metadata': 'https://document-api.company-information.service.gov.uk/document/nF7Zp53hYlSAnYpyZKAQyH-NagJ_hor8Ndek_n1nHQU'}}
{'transaction_id': 'MzI4MDkwMTA0MWFkaXF6a2N4', 'barcode': 'X9FY88LU', 'type': 'CS01', 'date': '2020-10-18', 'category': 'confirmation-statement', 'description': 'confirmation-statement-with-no-updates', 'description_values': {'made_up_date': '2020-10-06'}, 'pages': 3, 'action_date': '2020-10-06', 'links': {'self': '/company/12247029/filing-history/MzI4MDkwMTA0MWFkaXF6a2N4', 'document_metadata': 'https://document-api.company-information.service.gov.uk/document/m-DtKG1hY6P9TuKfx1acUfSE4BAQJWjx18d383DidIc'}}
{'transaction_id': 'MzI0NjA5MzU5M2FkaXF6a2N4', 'barcode': 'X8FGLGQJ', 'type': 'NEWINC', 'date': '2019-10-07', 'category': 'incorporation', 'associated_filings': [{'category': 'incorporation', 'date': '2019-10-07', 'description': 'model-articles-adopted', 'type': 'MODEL ARTICLES'}, {'category': 'capital', 'date': '2019-10-07', 'description': 'statement-of-capital', 'type': 'SH01', 'description_values': {'date': '2019-10-07', 'capital': [{'currency': 'GBP', 'figure': '1'}]}, 'action_date': '2019-10-07'}], 'description': 'incorporation-company', 'pages': 10, 'links': {'self': '/company/12247029/filing-history/MzI0NjA5MzU5M2FkaXF6a2N4', 'document_metadata': 'https://document-api.company-information.service.gov.uk/document/sThMLR0jEHVIzpSkH0Dv8Wb4lZ6FUp5TIW-blcxyEh4'}}

In [77]:
x = pd.DataFrame.from_dict(data["items"])

In [59]:
x = x[["transaction_id","barcode","type","date","category","subcategory","paper_filed","links"]]

In [60]:
# Charges
data = get(f"/company/{company_number}/charges", params={"items_per_page": 100, "start_index":0})
data

200

{'etag': '54a907a708ff44e333154169a9d85512c06417cc',
 'total_count': 87,
 'unfiltered_count': 87,
 'satisfied_count': 18,
 'part_satisfied_count': 0,
 'items': [{'etag': '51fe069c10b6eeb0ff2ae5421887ea568e9d0990',
   'charge_code': '000020650090',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 90,
   'status': 'outstanding',
   'delivered_on': '2026-05-08',
   'created_on': '2026-05-06',
   'particulars': {'type': 'brief-description',
    'description': 'N/A.',
    'contains_fixed_charge': True},
   'more_than_four_persons_entitled': True,
   'persons_entitled': [{'name': "The Society Incorporated by Lloyd's Act 1871 by the Name of Lloyd's"},
    {'name': 'The Trustees (As Defined in the Instrument)'},
    {'name': 'The Beneficiaries (As Defined in the Instrument)'},
    {'name': 'The Premiums Trustees (As Defined in the Instrument)'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2026-05-08',
     'links': {'filing': '/company/00002065/filing-history/MzUyMDQ1NzU4MWFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/k7RobJw5L_IVPeA-mnyA6990Dl4'}},
  {'etag': 'a7e0c4d698c20ed5454b25587bbf5c3fbf908fb0',
   'charge_code': '000020650089',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 89,
   'status': 'outstanding',
   'delivered_on': '2025-06-30',
   'created_on': '2025-06-23',
   'particulars': {'type': 'brief-description',
    'description': 'N/A.',
    'contains_fixed_charge': True},
   'more_than_four_persons_entitled': True,
   'persons_entitled': [{'name': "The Society Incorporated by Lloyd's Act 1871 by the Name of Lloyd's"},
    {'name': 'The Trustees (As Defined in the Instrument)'},
    {'name': 'The Beneficiaries (As Defined in the Instrument)'},
    {'name': 'The Premiums Trustees (As Defined in the Instrument)'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2025-06-30',
     'links': {'filing': '/company/00002065/filing-history/MzQ3MTkzOTM1OGFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/-5jHzmgIkfrEPLZwPm7B0Lb-hFw'}},
  {'etag': '6e8315b09b34d959a6065ec9cb798df48c0c6f5f',
   'charge_code': '000020650088',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 88,
   'status': 'outstanding',
   'delivered_on': '2025-03-18',
   'created_on': '2025-03-18',
   'particulars': {'type': 'brief-description',
    'description': 'N/A.',
    'contains_fixed_charge': True},
   'more_than_four_persons_entitled': True,
   'persons_entitled': [{'name': "The Society Incorporated by Lloyd's Act 1871 by the Name of Lloyd's"},
    {'name': 'The Trustees (As Defined in the Instrument)'},
    {'name': 'The Beneficiaries (As Defined in the Instrument)'},
    {'name': 'The Premiums Trustees (As Defined in the Instrument)'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2025-03-18',
     'links': {'filing': '/company/00002065/filing-history/MzQ1OTA4Nzc1OGFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/t5EdSnhz-xuPfTHV98UlJ-OwSJQ'}},
  {'etag': '8b98dba1da4c4fa9fd859b8554e31f4432bd9b35',
   'charge_code': '000020650087',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 87,
   'status': 'outstanding',
   'delivered_on': '2025-03-17',
   'created_on': '2025-03-11',
   'particulars': {'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': 'Kfw as Assignee'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2025-03-17',
     'links': {'filing': '/company/00002065/filing-history/MzQ1ODg2ODE3NGFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/w7t6sAi91v0cdsR-imPDwPpwtJ4'}},
  {'etag': '0d751a48fa558521449c14cee3adf28a6417430b',
   'charge_code': '000020650086',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 86,
   'status': 'outstanding',
   'delivered_on': '2025-03-17',
   'created_on': '2025-03-11',
   'particulars': {'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': 'Kfw as Assignee'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2025-03-17',
     'links': {'filing': '/company/00002065/filing-history/MzQ1ODg2NjMyN2FkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/TP76wvyn09yKtWKrn_FEN798yco'}},
  {'etag': '6c5dd5ac691992f9fa504b721125ca0a96bfd0fa',
   'charge_code': '000020650085',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 85,
   'status': 'outstanding',
   'delivered_on': '2025-03-17',
   'created_on': '2025-03-11',
   'particulars': {'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': 'Kfw as Assignee'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2025-03-17',
     'links': {'filing': '/company/00002065/filing-history/MzQ1ODg3MDI0MWFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/sUYa08SJ_hsGi_2YPLODZn59x0U'}},
  {'etag': '8e80412a3aad4ec17a3292fd60043c7767724c60',
   'charge_code': '000020650084',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 84,
   'status': 'outstanding',
   'delivered_on': '2025-03-17',
   'created_on': '2025-03-11',
   'particulars': {'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': 'Kfw as Assignee'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2025-03-17',
     'links': {'filing': '/company/00002065/filing-history/MzQ1ODg2ODgxNmFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/hwq4B2ZiCYuDI_o7ELcH825BcWA'}},
  {'etag': '1d804bb736db091f117a145b75946540584e70ad',
   'charge_code': '000020650083',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 83,
   'status': 'outstanding',
   'delivered_on': '2024-05-31',
   'created_on': '2024-05-29',
   'particulars': {'type': 'brief-description',
    'description': 'N/A.',
    'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': 'Lloyds Banking Group Pensions Trustees Limited (In Its Capacity as Trustee of Lloyds Bank Pension Scheme No. 2) (and Its Successors in Title and Permitted Transferees)'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2024-05-31',
     'links': {'filing': '/company/00002065/filing-history/MzQyMzg4ODkzM2FkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/NXfViU6qgkwrSmPwgEQEr97PprI'}},
  {'etag': '51cde4ebbe042b44437034e46589e716273d3b58',
   'charge_code': '000020650082',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 82,
   'status': 'outstanding',
   'delivered_on': '2024-05-31',
   'created_on': '2024-05-29',
   'particulars': {'type': 'brief-description',
    'description': 'N/A.',
    'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': 'Lloyds Banking Group Pensions Trustees Limited (In Its Capacity as Trustee of Lloyds Bank Pension Scheme No. 1) (and Its Successors in Title and Permitted Transferees)'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2024-05-31',
     'links': {'filing': '/company/00002065/filing-history/MzQyMzg4ODAyMGFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/sqOuJFhrEaqTFG3UsEXwTTvJQJ4'}},
  {'etag': 'aba456d8e85b9bd3a2d6ea32c03e33a0dba8bae1',
   'charge_code': '000020650081',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 81,
   'status': 'outstanding',
   'delivered_on': '2023-12-01',
   'created_on': '2023-11-28',
   'particulars': {'type': 'brief-description',
    'description': 'N/A.',
    'contains_fixed_charge': True},
   'more_than_four_persons_entitled': True,
   'persons_entitled': [{'name': "The Society Incorporated by Lloyd's Act 1871 by the Name of Lloyd's"},
    {'name': 'The Trustees (As Defined in the Instrument)'},
    {'name': 'The Beneficiaries (As Defined in the Instrument)'},
    {'name': 'The Premiums Trustees (As Defined in the Instrument)'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2023-12-01',
     'links': {'filing': '/company/00002065/filing-history/MzQwMjMxOTkxOGFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/uqqr-sNMbbzitxLn3XSOCkT9bpo'}},
  {'etag': 'b72c8f42095dbb3d423f72c6a2f33a0257259e49',
   'charge_code': '000020650080',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 80,
   'status': 'outstanding',
   'delivered_on': '2023-06-27',
   'created_on': '2023-06-08',
   'particulars': {'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': 'The Bank of New York Mellon'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2023-06-27',
     'links': {'filing': '/company/00002065/filing-history/MzM4NDMyODk5MGFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/8TNaa5BBTlsvFAclqN1kbNmkYfQ'}},
  {'etag': 'dbafbba351f687c949f5ef773d5a1a9a42bcd52b',
   'charge_code': '000020650079',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 79,
   'status': 'outstanding',
   'delivered_on': '2022-12-16',
   'created_on': '2022-12-14',
   'particulars': {'type': 'brief-description',
    'description': 'N/A.',
    'contains_fixed_charge': True},
   'more_than_four_persons_entitled': True,
   'persons_entitled': [{'name': "The Society Incorporated by Lloyd's Act 1871 by the Name of Lloyd's"},
    {'name': 'The Trustees (As Defined in the Instrument)'},
    {'name': 'The Beneficiaries (As Defined in the Instrument)'},
    {'name': 'The Premiums Trustees (As Defined in the Instrument)'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2022-12-16',
     'links': {'filing': '/company/00002065/filing-history/MzM2MjY3NjAwNmFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/tc00SVNvCe4mkiRibLnBR-xSzBA'}},
  {'etag': 'd6b9776c589bbf43644229bdf07e8ca31e3c5fc8',
   'charge_code': '000020650078',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 78,
   'status': 'outstanding',
   'delivered_on': '2021-10-13',
   'created_on': '2021-09-28',
   'particulars': {'type': 'brief-description',
    'description': 'N/A.',
    'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': 'The Bank of New York Mellon, London Branch'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2021-10-13',
     'links': {'filing': '/company/00002065/filing-history/MzMxNjg5MjQ0M2FkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/lUwVZ5flwzxE9FRxFopx0MlexeI'}},
  {'etag': 'da2133af4be66c6260965599eb7477025b22b99b',
   'charge_code': '000020650077',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 77,
   'status': 'outstanding',
   'delivered_on': '2021-01-08',
   'created_on': '2021-01-06',
   'particulars': {'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': "Fontwell Ii Securities 2020 Designated Activity Company, Registered Office at 5TH Floor the Exchange, George's Dock, Ifsc, Dublin 1, D01W3P9, Ireland"}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2021-01-08',
     'links': {'filing': '/company/00002065/filing-history/MzI4ODA1Mzc4MmFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/BBs2tDqdGeAmP-x1LEa3QG3fZPU'}},
  {'etag': '23c44b969107e2ff60c29773bf01afc715ff1378',
   'charge_code': '000020650076',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 76,
   'status': 'outstanding',
   'delivered_on': '2020-12-03',
   'created_on': '2020-12-02',
   'particulars': {'type': 'brief-description',
    'description': 'N/A.',
    'contains_fixed_charge': True},
   'more_than_four_persons_entitled': True,
   'persons_entitled': [{'name': "The Society Incorporated by Lloyd's Act 1871 by the Name of Lloyd's"},
    {'name': 'The Trustees (As Defined in the Instrument)'},
    {'name': 'The Beneficiaries (As Defined in the Instrument)'},
    {'name': 'The Premiums Trustees (As Defined in the Instrument)'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2020-12-03',
     'links': {'filing': '/company/00002065/filing-history/MzI4NTA4MTY1OWFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/Y81Dx4FNCv1qnbPv93tlNlagUeU'}},
  {'etag': '952a23da8388d7e9fa7c45d0aeec6a79d4ce5c7c',
   'charge_code': '000020650075',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 75,
   'status': 'outstanding',
   'delivered_on': '2020-12-03',
   'created_on': '2020-12-02',
   'particulars': {'type': 'brief-description',
    'description': 'N/A.',
    'contains_fixed_charge': True},
   'more_than_four_persons_entitled': True,
   'persons_entitled': [{'name': "The Society Incorporated by Lloyd's Act 1871 by the Name of Lloyd's"},
    {'name': 'The Trustees (As Defined in the Instrument)'},
    {'name': 'The Beneficiaries (As Defined in the Instrument)'},
    {'name': 'The Premiums Trustees (As Defined in the Instrument)'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2020-12-03',
     'links': {'filing': '/company/00002065/filing-history/MzI4NTA4MTE5MWFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/SWlPGz3BUZ8f9kywDgEPxnSWRIU'}},
  {'etag': '07c8a4c58501f6a5d2bff0c6062185ddf0b2afbe',
   'charge_code': '000020650074',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 74,
   'status': 'outstanding',
   'delivered_on': '2019-12-31',
   'created_on': '2019-12-30',
   'particulars': {'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': 'Wetherby Iii Securities 2019 Designated Activity Company'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2019-12-31',
     'links': {'filing': '/company/00002065/filing-history/MzI1MzQyMjYwMWFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/R9nftJr3cO5nJThHVvhJz-sxjVk'}},
  {'etag': '8c18fdba772ea1ec3882c9bc1cb1eade3fb32c30',
   'charge_code': '000020650073',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 73,
   'status': 'outstanding',
   'delivered_on': '2019-10-25',
   'created_on': '2019-10-18',
   'particulars': {'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': 'Housing Association Risk Transfer 2019 Designated Activity Company'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2019-10-25',
     'links': {'filing': '/company/00002065/filing-history/MzI0NzcyOTYxMGFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/9E-rfjvjtL3HiaaXu1UD_Y2Hakk'}},
  {'etag': '5c7c3eb8aa6e4d9e8af43b01c23b28fcbfedaa7a',
   'charge_code': '000020650072',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 72,
   'status': 'outstanding',
   'delivered_on': '2019-10-10',
   'created_on': '2019-10-08',
   'particulars': {'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': 'Bnp Paribas'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2019-10-10',
     'links': {'filing': '/company/00002065/filing-history/MzI0NjU0MzI5MGFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/Lwj8K4zMMPGqvPb_NzlYFqbdHec'}},
  {'etag': 'b4e4513bcd9a6b00cd22f98ebdbfd93010621a7f',
   'charge_code': '000020650071',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 71,
   'status': 'outstanding',
   'delivered_on': '2019-10-08',
   'created_on': '2019-09-18',
   'particulars': {'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': 'Bnp Paribas'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2019-10-08',
     'links': {'filing': '/company/00002065/filing-history/MzI0NjI5MTA5NGFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/sYTfJJZsNODwfRF41xhO4oT419U'}},
  {'etag': 'be3ac446784d31ab8db253e8e8fabbfd222cb2d6',
   'charge_code': '000020650070',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 70,
   'status': 'outstanding',
   'delivered_on': '2019-09-03',
   'created_on': '2019-09-01',
   'particulars': {'contains_floating_charge': True,
    'contains_fixed_charge': True},
   'persons_entitled': [{'name': 'Bnp Paribas'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2019-09-03',
     'links': {'filing': '/company/00002065/filing-history/MzI0NDEwNDA4M2FkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/fKzmphwN6zuQ9c6z4QomPL7nTOg'}},
  {'etag': '9a77d2efbe01df8653b7af826dc865caeec656d1',
   'charge_code': '000020650069',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 69,
   'status': 'outstanding',
   'delivered_on': '2019-09-10',
   'created_on': '2019-09-01',
   'particulars': {'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': 'Ubs Ag (And Its Successors in Title and Permitted Transferees)'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2019-09-10',
     'links': {'filing': '/company/00002065/filing-history/MzI0MzkxNzk0OWFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/baOeQZbFIZaCW_WztYjZN842lbs'}},
  {'etag': 'd5ef2f15cf81a94b2ad1650751d94b78ba8b97cc',
   'charge_code': '000020650068',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 68,
   'status': 'outstanding',
   'delivered_on': '2019-09-04',
   'created_on': '2019-09-01',
   'particulars': {'type': 'brief-description',
    'description': 'N/A.',
    'contains_fixed_charge': True,
    'contains_negative_pledge': True},
   'persons_entitled': [{'name': 'Deutsche Bank Ag'}],
   'transactions': [{'filing_type': 'create-charge-with-deed',
     'delivered_on': '2019-09-04',
     'links': {'filing': '/company/00002065/filing-history/MzI0MzQ1MDkzMmFkaXF6a2N4'}}],
   'links': {'self': '/company/00002065/charges/qA5pYVyxKnMQepZaekuYX5PDIz0'}},
  {'etag': 'b59c27c277420829649535783e989a92ad4bc8b1',
   'charge_code': '000020650067',
   'classification': {'type': 'charge-description',
    'description': 'A registered charge'},
   'charge_number': 67,
   'status': 'outstanding',
   'delivered_on': '2019-08-29',
   'created_on': '2019-08-28',
   'particulars': {'type': 'brief-description',
    'description': 'N/A.',
    'contains_fixed_charge': True,
    'contains_negative_pledge': True},

In [61]:
x = pd.DataFrame.from_dict(data["items"])

In [62]:
x

,etag,charge_code,classification,charge_number,status,delivered_on,created_on,particulars,more_than_four_persons_entitled,persons_entitled,transactions,links,satisfied_on,assets_ceased_released,secured_details
0,51fe069c10b6eeb0ff2ae5421887ea568e9d0990,000020650090,"{'type': 'charge-description', 'description': ...",90,outstanding,2026-05-08,2026-05-06,"{'type': 'brief-description', 'description': '...",True,[{'name': 'The Society Incorporated by Lloyd's...,"[{'filing_type': 'create-charge-with-deed', 'd...",{'self': '/company/00002065/charges/k7RobJw5L_...,NaN,NaN,NaN
1,a7e0c4d698c20ed5454b25587bbf5c3fbf908fb0,000020650089,"{'type': 'charge-description', 'description': ...",89,outstanding,2025-06-30,2025-06-23,"{'type': 'brief-description', 'description': '...",True,[{'name': 'The Society Incorporated by Lloyd's...,"[{'filing_type': 'create-charge-with-deed', 'd...",{'self': '/company/00002065/charges/-5jHzmgIkf...,NaN,NaN,NaN
2,6e8315b09b34d959a6065ec9cb798df48c0c6f5f,000020650088,"{'type': 'charge-description', 'description': ...",88,outstanding,2025-03-18,2025-03-18,"{'type': 'brief-description', 'description': '...",True,[{'name': 'The Society Incorporated by Lloyd's...,"[{'filing_type': 'create-charge-with-deed', 'd...",{'self': '/company/00002065/charges/t5EdSnhz-x...,NaN,NaN,NaN
3,8b98dba1da4c4fa9fd859b8554e31f4432bd9b35,000020650087,"{'type': 'charge-description', 'description': ...",87,outstanding,2025-03-17,2025-03-11,"{'contains_fixed_charge': True, 'contains_nega...",NaN,[{'name': 'Kfw as Assignee'}],"[{'filing_type': 'create-charge-with-deed', 'd...",{'self': '/company/00002065/charges/w7t6sAi91v...,NaN,NaN,NaN
4,0d751a48fa558521449c14cee3adf28a6417430b,000020650086,"{'type': 'charge-description', 'description': ...",86,outstanding,2025-03-17,2025-03-11,"{'contains_fixed_charge': True, 'contains_nega...",NaN,[{'name': 'Kfw as Assignee'}],"[{'filing_type': 'create-charge-with-deed', 'd...",{'self': '/company/00002065/charges/TP76wvyn09...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,NaN,NaN,"{'type': 'charge-description', 'description': ...",5,fully-satisfied,1997-08-20,1997-08-04,"{'type': 'short-particulars', 'description': '...",NaN,[{'name': 'Federal Reserve Bank of Atlanta'}],[{'filing_type': 'create-charge-pre-2006-compa...,{'self': '/company/00002065/charges/BVuTiVO3og...,1998-02-23,NaN,"{'type': 'amount-secured', 'description': 'All..."
83,NaN,NaN,"{'type': 'charge-description', 'description': ...",3,fully-satisfied,1992-12-15,1992-11-26,"{'type': 'short-particulars', 'description': '...",NaN,[{'name': 'The Governor and Company of the Ban...,[{'filing_type': 'create-charge-pre-2006-compa...,{'self': '/company/00002065/charges/qhRzwPzbyy...,2000-03-06,NaN,"{'type': 'amount-secured', 'description': 'All..."
84,NaN,NaN,"{'type': 'charge-description', 'description': ...",4,fully-satisfied,1985-07-26,1985-07-15,"{'type': 'short-particulars', 'description': '...",NaN,[{'name': 'Lloyds Bank PLC'}],"[{'filing_type': 'create-charge', 'delivered_o...",{'self': '/company/00002065/charges/qvoAk8xMDE...,1993-06-17,NaN,"{'type': 'amount-secured', 'description': 'All..."
85,NaN,NaN,"{'type': 'charge-description', 'description': ...",2,fully-satisfied,1984-07-10,1984-06-22,"{'type': 'short-particulars', 'description': '...",NaN,[{'name': 'Schroder Life Assurance Limited'}],"[{'filing_type': 'create-charge', 'delivered_o...",{'self': '/company/00002065/charges/O0brOUWmIn...,1984-12-05,NaN,"{'type': 'amount-secured', 'description': 'All..."
86,NaN,NaN,"{'type': 'charge-description', 'description': ...",1,fully-satisfied,1981-12-30,1981-12-23,"{'type': 'short-particulars', 'description': '...",NaN,[{'name': 'Watneys Southern Limited'}],"[{'filing_type': 'create-charge', 'delivered_o...",{'self': '/company/00002065/charges/w7ob-RdpBd...,1982-08-20,NaN,"{'type': 'amount-secured', 'description': 'Any..."

In [63]:
data = get(f"/company/{company_number}/persons-with-significant-control")
data

# x = pd.DataFrame.from_dict(data)
# x

200

{'items_per_page': 25,
 'items': [{'etag': '0110718503ce0622dd453f7f01c75cc97c3b80c8',
   'notified_on': '2016-04-06',
   'name': 'Lloyds Banking Group Plc',
   'links': {'self': '/company/00002065/persons-with-significant-control/corporate-entity/rTHhnY4-WO4nqU_grhl-RUEB6z0'},
   'identification': {'legal_form': 'Public Limited Company',
    'legal_authority': 'United Kingdom (Scotland)',
    'country_registered': 'Scotland',
    'place_registered': 'Companies House',
    'registration_number': 'Sc095000'},
   'ceased': False,
   'kind': 'corporate-entity-person-with-significant-control',
   'address': {'address_line_1': 'The Mound',
    'country': 'United Kingdom',
    'locality': 'Edinburgh',
    'postal_code': 'EH1 1YZ'},
   'natures_of_control': ['ownership-of-shares-75-to-100-percent',
    'voting-rights-75-to-100-percent',
    'right-to-appoint-and-remove-directors']}],
 'start_index': 0,
 'total_results': 1,
 'active_count': 1,
 'ceased_count': 0,
 'links': {'self': '/company/00002065/persons-with-significant-control'}}

In [64]:
data = get(f"/company/{company_number}/officers")

temp = data["items"][0]["links"]["self"].split("/")

200

In [65]:
x = pd.DataFrame.from_dict(data["items"])
x[10:15]

,etag,address,appointed_on,is_pre_1992_appointment,links,name,officer_role,person_number,country_of_residence,date_of_birth,nationality,former_names,identity_verification_details,resigned_on,appointed_before
10,cf24bc3fa139ab0d57532bd822f36cbfbc18f463,"{'address_line_1': 'Gresham Street', 'country'...",2021-08-16,False,{'self': '/company/00002065/appointments/VIRkO...,"NUNN, Charles Alan",director,286317400001,United Kingdom,"{'month': 9, 'year': 1971}",British,NaN,{'anti_money_laundering_supervisory_bodies': [...,NaN,NaN
11,a4d7a5e57dc6cff43fc17dbc39798848c999bffc,"{'address_line_1': 'Gresham Street', 'country'...",2022-11-01,False,{'self': '/company/00002065/appointments/ZKO8d...,"TURNER, Catherine Lucy",director,180221240001,United Kingdom,"{'month': 6, 'year': 1963}",British,NaN,{'anti_money_laundering_supervisory_bodies': [...,NaN,NaN
12,d91ebca67f940381c3fb74ca41876cb546c22f9e,"{'address_line_1': 'Old Broad Street', 'countr...",2025-06-16,False,{'self': '/company/00002065/appointments/nguSG...,"VOGELZANG, Christiaan Franciscus Henricus Herman",director,336954640001,Netherlands,"{'month': 11, 'year': 1962}",Dutch,NaN,{'anti_money_laundering_supervisory_bodies': [...,NaN,NaN
13,c8cdf79e126d92dcccbdaf34954c6b5547267759,"{'address_line_1': 'Gresham Street', 'country'...",2020-03-01,False,{'self': '/company/00002065/appointments/rmuDT...,"WOODS, Catherine Marie",director,268099680001,Ireland,"{'month': 9, 'year': 1962}",Irish,"[{'forenames': 'CATHERINE', 'surname': 'MARIE ...",{'anti_money_laundering_supervisory_bodies': [...,NaN,NaN
14,3bdaa1003f7b020a8dc53ce11bf5010b30a0f93d,"{'address_line_1': 'The Mound', 'locality': 'E...",2009-01-16,False,{'self': '/company/00002065/appointments/j0HG6...,"BAINES, Harold Francis",secretary,207382860001,NaN,NaN,British,NaN,NaN,2012-08-01,NaN

In [66]:
data = get(f"/company/{company_number}/officers")
data

200

{'active_count': 14,
 'etag': '3bdaa1003f7b020a8dc53ce11bf5010b30a0f93d',
 'items': [{'etag': '3bdaa1003f7b020a8dc53ce11bf5010b30a0f93d',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2019-07-01',
   'is_pre_1992_appointment': False,
   'links': {'self': '/company/00002065/appointments/s69oD4uF8aj7KGtzyBtyTyPD-2Q',
    'officer': {'appointments': '/officers/xeS7C_yO94cCW7iWxHLPA5thIaw/appointments'}},
   'name': 'CHEETHAM, Catharine Lucy',
   'officer_role': 'secretary',
   'person_number': '260163850001'},
  {'etag': 'a4694fa692a5dc6636fa40a6ed90a8f194ad2fb4',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2019-01-01',
   'is_pre_1992_appointment': False,
   'country_of_residence': 'United Kingdom',
   'date_of_birth': {'month': 8, 'year': 1971},
   'links': {'self': '/company/00002065/appointments/-KQnizAfBldkppRRQkmGJivvaMQ',
    'officer': {'appointments': '/officers/yrErggbY0ELBvgk6Yi1vuoVdZy0/appointments'}},
   'name': 'BENTLEY, Sarah Elise',
   'nationality': 'British',
   'officer_role': 'director',
   'former_names': [{'forenames': 'SARAH ELISE', 'surname': 'FAUX'}],
   'person_number': '253981500001',
   'identity_verification_details': {'anti_money_laundering_supervisory_bodies': ['Institute of Chartered Accountants in England and Wales (ICAEW)'],
    'appointment_verification_end_on': '9999-12-31',
    'appointment_verification_start_on': '2026-05-19',
    'authorised_corporate_service_provider_name': 'ERNST & YOUNG LLP ACSP',
    'identity_verified_on': '2025-09-11',
    'preferred_name': 'Sarah Elise Bentley'}},
  {'etag': '13e917e694c9a0519fae750c55efd98fc62e084d',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2024-08-01',
   'is_pre_1992_appointment': False,
   'country_of_residence': 'United Kingdom',
   'date_of_birth': {'month': 10, 'year': 1960},
   'links': {'self': '/company/00002065/appointments/yvrkD78iH00iu9PzSw1Bzp7ZOpc',
    'officer': {'appointments': '/officers/scLBniYWEUNs8jrfqP7Tcc4hIN0/appointments'}},
   'name': 'BOSTOCK, Nathan Mark',
   'nationality': 'British',
   'officer_role': 'director',
   'person_number': '325932190001',
   'identity_verification_details': {'appointment_verification_end_on': '9999-12-31',
    'appointment_verification_start_on': '2026-05-19'}},
  {'etag': '687727d24509d2a89e0bf3caeb51a45f6025ce60',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2020-10-01',
   'is_pre_1992_appointment': False,
   'country_of_residence': 'United Kingdom',
   'date_of_birth': {'month': 5, 'year': 1959},
   'links': {'self': '/company/00002065/appointments/mmKktvLNAjxeNIvyn7WJX7DWp5s',
    'officer': {'appointments': '/officers/7yuRlloqX3wFKusLwhWfS6nU5Is/appointments'}},
   'name': 'BUDENBERG, Robin Francis',
   'nationality': 'British',
   'officer_role': 'director',
   'person_number': '275111340001',
   'identity_verification_details': {'anti_money_laundering_supervisory_bodies': ['Institute of Chartered Accountants in England and Wales (ICAEW)'],
    'appointment_verification_end_on': '9999-12-31',
    'appointment_verification_start_on': '2026-05-19',
    'authorised_corporate_service_provider_name': 'ERNST & YOUNG LLP ACSP',
    'identity_verified_on': '2025-09-04',
    'preferred_name': 'Robin Francis Budenberg'}},
  {'etag': '7400f92505321905dcef460a664b7e22a2837233',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2019-08-01',
   'is_pre_1992_appointment': False,
   'country_of_residence': 'United Kingdom',
   'date_of_birth': {'month': 7, 'year': 1968},
   'links': {'self': '/company/00002065/appointments/0TQ1rlH_wsFRoYcwpZwlGpSXM0I',
    'officer': {'appointments': '/officers/1iYAU2EUIQbWz5InBptilccbifU/appointments'}},
   'name': 'CHALMERS, William Leon David',
   'nationality': 'British',
   'officer_role': 'director',
   'person_number': '261222830001',
   'identity_verification_details': {'anti_money_laundering_supervisory_bodies': ['Institute of Chartered Accountants in England and Wales (ICAEW)'],
    'appointment_verification_end_on': '9999-12-31',
    'appointment_verification_start_on': '2026-05-19',
    'authorised_corporate_service_provider_name': 'ERNST & YOUNG LLP ACSP',
    'identity_verified_on': '2025-10-31',
    'preferred_name': 'William Leon David Chalmers'}},
  {'etag': 'df9194ada6eeb9532e32686925d39d04bab212d1',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2019-01-01',
   'is_pre_1992_appointment': False,
   'country_of_residence': 'Gibraltar',
   'date_of_birth': {'month': 6, 'year': 1956},
   'links': {'self': '/company/00002065/appointments/LODfGAZb76E1hLwY5XFFUURdVQs',
    'officer': {'appointments': '/officers/hOuqj2CWt_-paFXU9BOKd7GnzlU/appointments'}},
   'name': 'GILLIGAN, Brendan Edward',
   'nationality': 'Irish',
   'officer_role': 'director',
   'person_number': '253991320001',
   'identity_verification_details': {'anti_money_laundering_supervisory_bodies': ['Institute of Chartered Accountants in England and Wales (ICAEW)'],
    'appointment_verification_end_on': '9999-12-31',
    'appointment_verification_start_on': '2026-05-19',
    'authorised_corporate_service_provider_name': 'ERNST & YOUNG LLP ACSP',
    'identity_verified_on': '2025-09-03',
    'preferred_name': 'Brendan Edward Gilligan'}},
  {'etag': 'c7c87f72225f1be70abd4ae5056add55619861ae',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2019-01-01',
   'is_pre_1992_appointment': False,
   'country_of_residence': 'England',
   'date_of_birth': {'month': 2, 'year': 1966},
   'links': {'self': '/company/00002065/appointments/1AS6NlnMjMTjexK-LCHQORR7RU4',
    'officer': {'appointments': '/officers/EssjpJuWp7-FrJcX9GWGBFX43HI/appointments'}},
   'name': 'HINSHELWOOD, Nigel Grant',
   'nationality': 'British',
   'officer_role': 'director',
   'person_number': '136686130001',
   'identity_verification_details': {'anti_money_laundering_supervisory_bodies': ['Institute of Chartered Accountants in England and Wales (ICAEW)'],
    'appointment_verification_end_on': '9999-12-31',
    'appointment_verification_start_on': '2026-05-19',
    'authorised_corporate_service_provider_name': 'ERNST & YOUNG LLP ACSP',
    'identity_verified_on': '2025-09-03',
    'preferred_name': 'Nigel Grant Hinshelwood'}},
  {'etag': '7cffb924a87840af40bec278f2e5a7aecfe3d863',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2019-12-01',
   'is_pre_1992_appointment': False,
   'country_of_residence': 'England',
   'date_of_birth': {'month': 9, 'year': 1967},
   'links': {'self': '/company/00002065/appointments/UqNJ4fJ9ZUwEW0t8tl2L6JbnXNM',
    'officer': {'appointments': '/officers/QfBR3NmISzEusrexrXk9m8SLYMY/appointments'}},
   'name': 'LEGG, Sarah Catherine',
   'nationality': 'British',
   'officer_role': 'director',
   'person_number': '265243030001',
   'identity_verification_details': {'anti_money_laundering_supervisory_bodies': ['Institute of Chartered Accountants in England and Wales (ICAEW)'],
    'appointment_verification_end_on': '9999-12-31',
    'appointment_verification_start_on': '2026-05-19',
    'authorised_corporate_service_provider_name': 'ERNST & YOUNG LLP ACSP',
    'identity_verified_on': '2025-09-03',
    'preferred_name': 'Sarah Catherine Legg'}},
  {'etag': 'c6ebb69a2aceb182b86d5386d788d93e9a11eddd',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2018-10-01',
   'is_pre_1992_appointment': False,
   'country_of_residence': 'United Kingdom',
   'date_of_birth': {'month': 12, 'year': 1963},
   'links': {'self': '/company/00002065/appointments/8Tj3y-2AFEL2yRIcBV0g2Op5cas',
    'officer': {'appointments': '/officers/PxXzPohZ8msIh_ST1kCFijwR4lo/appointments'}},
   'name': 'MACKENZIE, Amanda Felicity',
   'nationality': 'British',
   'officer_role': 'director',
   'former_names': [{'surname': 'AMANDA POORTA'}, {'surname': 'POORTA'}],
   'person_number': '94059020001',
   'identity_verification_details': {'anti_money_laundering_supervisory_bodies': ['Institute of Chartered Accountants in England and Wales (ICAEW)'],
    'appointment_verification_end_on': '9999-12-31',
    'appointment_verification_start_on': '2026-05-19',
    'authorised_corporate_service_provider_name': 'ERNST & YOUNG LLP ACSP',
    'identity_verified_on': '2025-09-02',
    'preferred_name': 'Amanda Felicity Mackenzie'}},
  {'etag': 'a70771ac22d8309f483ce8875a54ab7cd9fd9736',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2021-11-01',
   'is_pre_1992_appointment': False,
   'country_of_residence': 'United Kingdom',
   'date_of_birth': {'month': 8, 'year': 1974},
   'links': {'self': '/company/00002065/appointments/XLDcwhyCFp_XtN0E76IOd6T7jxE',
    'officer': {'appointments': '/officers/y4FjL7eDOYHo_toR1Fw4bjtyCOA/appointments'}},
   'name': 'MEHTA, Harmeen',
   'nationality': 'Indian',
   'officer_role': 'director',
   'person_number': '289066410002',
   'identity_verification_details': {'anti_money_laundering_supervisory_bodies': ['Institute of Chartered Accountants in England and Wales (ICAEW)'],
    'appointment_verification_end_on': '9999-12-31',
    'appointment_verification_start_on': '2026-05-19',
    'authorised_corporate_service_provider_name': 'ERNST & YOUNG LLP ACSP',
    'identity_verified_on': '2025-09-17',
    'preferred_name': 'Harmeen Mehta'}},
  {'etag': 'cf24bc3fa139ab0d57532bd822f36cbfbc18f463',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2021-08-16',
   'is_pre_1992_appointment': False,
   'country_of_residence': 'United Kingdom',
   'date_of_birth': {'month': 9, 'year': 1971},
   'links': {'self': '/company/00002065/appointments/VIRkO-iKwwCO4GzMXBL6Iqoi4xs',
    'officer': {'appointments': '/officers/jwRDr11bilqxSkcX6MQ5VwKdmuI/appointments'}},
   'name': 'NUNN, Charles Alan',
   'nationality': 'British',
   'officer_role': 'director',
   'person_number': '286317400001',
   'identity_verification_details': {'anti_money_laundering_supervisory_bodies': ['Institute of Chartered Accountants in England and Wales (ICAEW)'],
    'appointment_verification_end_on': '9999-12-31',
    'appointment_verification_start_on': '2026-05-19',
    'authorised_corporate_service_provider_name': 'ERNST & YOUNG LLP ACSP',
    'identity_verified_on': '2025-10-10',
    'preferred_name': 'Charles Alan Nunn'}},
  {'etag': 'a4d7a5e57dc6cff43fc17dbc39798848c999bffc',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2022-11-01',
   'is_pre_1992_appointment': False,
   'country_of_residence': 'United Kingdom',
   'date_of_birth': {'month': 6, 'year': 1963},
   'links': {'self': '/company/00002065/appointments/ZKO8devfaDd4X7886lBXpxKsSBs',
    'officer': {'appointments': '/officers/XuVrWFD29ipA65JPMktuTb8u8lg/appointments'}},
   'name': 'TURNER, Catherine Lucy',
   'nationality': 'British',
   'officer_role': 'director',
   'person_number': '180221240001',
   'identity_verification_details': {'anti_money_laundering_supervisory_bodies': ['Institute of Chartered Accountants in England and Wales (ICAEW)'],
    'appointment_verification_end_on': '9999-12-31',
    'appointment_verification_start_on': '2026-05-19',
    'authorised_corporate_service_provider_name': 'ERNST & YOUNG LLP ACSP',
    'identity_verified_on': '2025-09-08',
    'preferred_name': 'Catherine Lucy Turner'}},
  {'etag': 'd91ebca67f940381c3fb74ca41876cb546c22f9e',
   'address': {'address_line_1': 'Old Broad Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2N 1HZ',
    'premises': '33'},
   'appointed_on': '2025-06-16',
   'is_pre_1992_appointment': False,
   'country_of_residence': 'Netherlands',
   'date_of_birth': {'month': 11, 'year': 1962},
   'links': {'self': '/company/00002065/appointments/nguSGlYrM5AEJRh8qvFfx5OhhBk',
    'officer': {'appointments': '/officers/wBwARdY_9tNZ63t57ChDrbjJpJI/appointments'}},
   'name': 'VOGELZANG, Christiaan Franciscus Henricus Herman',
   'nationality': 'Dutch',
   'officer_role': 'director',
   'person_number': '336954640001',
   'identity_verification_details': {'anti_money_laundering_supervisory_bodies': ['Institute of Chartered Accountants in England and Wales (ICAEW)'],
    'appointment_verification_end_on': '9999-12-31',
    'appointment_verification_start_on': '2026-05-19',
    'authorised_corporate_service_provider_name': 'ERNST & YOUNG LLP ACSP',
    'identity_verified_on': '2025-09-03',
    'preferred_name': 'Christiaan Franciscus Henricus Herman Vogelzang'}},
  {'etag': 'c8cdf79e126d92dcccbdaf34954c6b5547267759',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2020-03-01',
   'is_pre_1992_appointment': False,
   'country_of_residence': 'Ireland',
   'date_of_birth': {'month': 9, 'year': 1962},
   'links': {'self': '/company/00002065/appointments/rmuDTVKllcKeYHakb_KYM6CI_og',
    'officer': {'appointments': '/officers/iAYQtAJPGyIgXp_Kwvs6WmOTdA0/appointments'}},
   'name': 'WOODS, Catherine Marie',
   'nationality': 'Irish',
   'officer_role': 'director',
   'former_names': [{'forenames': 'CATHERINE', 'surname': 'MARIE FEEHAN'}],
   'person_number': '268099680001',
   'identity_verification_details': {'anti_money_laundering_supervisory_bodies': ['Institute of Chartered Accountants in England and Wales (ICAEW)'],
    'appointment_verification_end_on': '9999-12-31',
    'appointment_verification_start_on': '2026-05-19',
    'authorised_corporate_service_provider_name': 'ERNST & YOUNG LLP ACSP',
    'identity_verified_on': '2025-09-10',
    'preferred_name': 'Catherine Marie Woods'}},
  {'etag': '3bdaa1003f7b020a8dc53ce11bf5010b30a0f93d',
   'address': {'address_line_1': 'The Mound',
    'locality': 'Edinburgh',
    'postal_code': 'EH1 1YZ'},
   'appointed_on': '2009-01-16',
   'is_pre_1992_appointment': False,
   'links': {'self': '/company/00002065/appointments/j0HG6iOYEaK9bd8fgPOtd88DkFo',
    'officer': {'appointments': '/officers/UVYLd1guq5H-xkND9DYPSli7OIU/appointments'}},
   'name': 'BAINES, Harold Francis',
   'nationality': 'British',
   'officer_role': 'secretary',
   'resigned_on': '2012-08-01',
   'person_number': '207382860001'},
  {'etag': '3bdaa1003f7b020a8dc53ce11bf5010b30a0f93d',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2014-01-01',
   'is_pre_1992_appointment': False,
   'links': {'self': '/company/00002065/appointments/Gwrt-s8HDlkuuFzmWgjEGNJmpO0',
    'officer': {'appointments': '/officers/QsqufKss8uQiAJEqIbq9llBInoY/appointments'}},
   'name': 'BOSTON, Marc-John',
   'officer_role': 'secretary',
   'resigned_on': '2014-11-02',
   'person_number': '184036140001'},
  {'etag': '3bdaa1003f7b020a8dc53ce11bf5010b30a0f93d',
   'address': {'address_line_1': 'Gresham Street',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2008-05-09',
   'is_pre_1992_appointment': False,
   'links': {'self': '/company/00002065/appointments/GogrHrfIMTDLRqQou80mCpHdpgI',
    'officer': {'appointments': '/officers/dcn0A5WXR8DuODZHSh2gtfJaAIg/appointments'}},
   'name': 'COLTMAN, Margaret Ann',
   'nationality': 'British',
   'officer_role': 'secretary',
   'resigned_on': '2009-01-16',
   'person_number': '15775050003'},
  {'etag': '3bdaa1003f7b020a8dc53ce11bf5010b30a0f93d',
   'address': {'address_line_1': 'Gresham Street',
    'country': 'United Kingdom',
    'locality': 'London',
    'postal_code': 'EC2V 7HN',
    'premises': '25'},
   'appointed_on': '2012-08-01',
   'is_pre_1992_appointment': False,
   'links': {'self': '/company/00002065/appointments/tYpkg8t-SLwifhFtkSRjBHGthys',
    'officer': {'appointments': '/officers/KGlN4cXPnUtD6fXycIfWBH-9FtQ/appointments'}},
   'name': 'DAVIES, Claire Anne',
   'officer_role': 'secretary',
   'resigned_on': '2013-12-31',
   'person_number': '171217370001'},
  {'etag': '3bdaa1003f7b020a8dc53ce11bf5010b30a0f93d',
   'address': {'address_line_1': 'Hunyani Ardleigh Road',
    'address_line_2': 'Little Bromley',
    'locality': 'Manningtree',
    'postal_code': 'CO11 2QA',
    'region': 'Essex'},
   'appointed_on': '1996-05-02',
   'is_pre_1992_appointment': False,
   'links': {'self': '/company/00002065/appointments/4x8iP2dV4LAl9n_Lh7tbA7nB--Y',
    'officer': {'appointments': '/officers/xbEtDTUKbWvPGHRfOYjGPPdqN0Y/appointments'}},
   'name': 'HATCHER, Michael Roger',
   'nationality': 'British',
   'officer_role': 'secretary',
   'resigned_on': '1999-06-30',
   'person_number': '6759000002'},
  {'etag': '3bdaa1003f7b020a8dc53ce11bf5010b30a0f93d',
   'address': {'address_line_1': 'White Cottage',
    'address_line_2': 'Wildhern',
    'locality': 'Andover',
    'postal_code': 'SP11 0JE',
    'region': 'Hampshire'},
   'appointed_on': '1995-12-28',
   'is_pre_1992_appointment': False,
   'links': {'self': '/company/00002065/appointments/lsk7zKlhz591PFJsLeaczQDuduw',
    'officer': {'appointments': '/officers/kbkLnx8uFBrTr8vaACF1h35Pcyw/appointments'}},
   'name': 'MARCH, Luke Henry Walter',
   'nationality': 'British',
   'officer_role': 'secretary',
   'resigned_on': '1996-05-02',
   'person_number': '63626070001'},
  {'etag': '3bdaa1003f7b020a8dc53ce11bf5010b30a0f93d',
   'address': {'address_line_1': '14 Marlyns Close',
    'address_line_2': 'Burpham',
    'locality': 'Guildford',
    'postal_code': 'GU4 7LR',
    'region': 'Surrey'},
   'appointed_on': '1999-06-30',
   'is_pre_1992_appointment': False,
   'links': {'self': '/company/00002065/appointments/iFegtBf62r9IR4XMOyRhPkwdV0A',
    'officer': {'appointments': '/officers/lBaKp9B0gm7EI3T38GJCU7PC5LA/appointments'}},
   'name': 'MICHIE, Alastair John',
   'nationality': 'British',
   'officer_role': 'secretary',
   'resigned_on': '2008-05-08',
   'person_number': '6770590001'},
  {'etag': '3bdaa1003f7b020a8dc53ce11bf5010b30a0f93d',
   'address': {'address_line_1': '14 Marlyns Close',
    'address_line_2': 'Burpham',
    'locality': 'Guildford',
    'postal_code': 'GU4 7LR',
    'region': 'Surrey'},
   'appointed_before': '1992-05-09',
   'is_pre_1992_appointment': True,
   'links': {'self': '/company/00002065/appointments/S2nmQzoTVcHvS-HovivSbZnRpHs',
    'officer': {'appointments': '/officers/lBaKp9B0gm7EI3T38GJCU7PC5LA/appointments'}},
   'name': 'MICHIE, Alastair John',
   'nationality': 'British',
   'officer_role': 'secretary',
   'resigned_on': '1995-12-28',
   'person_number': '6770590001'},
  {'etag': '3bdaa1003f7b020a8dc53ce11bf5010b30a0f93d',

In [73]:
# Useable APIs
#   - Charges - number of fully satisfied / outstanding charges, timeline, borrowing freqeuncy
#   - Officer - prominent figures in the company (tracked through person_number), likely can be used to 
#       track their history through different companies. In the companies themselves, we can see the 
#       number of resignations (resignation date)
#   - Person of Significant Influence - share holders, likely can use the same mechanisms as officers
#   - Account - only thing is probably the has_charges, history_of_insolvancy, next_accounts, 
#       sic_code(industry code) 

# All the companies can be tracked through their company numbers, which hopefully will be available in all 
# API channels